import { Kantone } from 'src/app/components/models/kantone';

export const Beiträge = {
  /*'0 Präludium: «Man muss sie spielen …» ': {
    karusselltitel: '0 Präludium: «Man muss sie spielen …» ',
    verzeichnispfad: 'Praeludium',
    beitragtitel: '0 Präludium: «Man muss sie spielen …» ',
    ort: 'Trouvaillen',
    bild: 'trouvaillen/bild1.jpg',
    autor: 'Rudolf Dellsberger',
    jahr: '2006',
    markierungen: [[45.13332, 10.02400]],
    kanton: Kantone.Trouvaillen,
  },

  '1 Christus und die Kirche': {
    karusselltitel: '1 Christus und die Kirche',
    verzeichnispfad: 'christusunddiekirche',
    beitragtitel: '1 Christus und die Kirche',
    ort: 'Trouvaillen',
    bild: 'trouvaillen/bild1.jpg',
    autor: 'Rudolf Dellsberger',
    jahr: '2006',
    markierungen: [[46.80787, 7.15951]],
    kanton: Kantone.Trouvaillen,
  },
*/
  'Église Saint-Jean-Baptiste': {
    karusselltitel: 'Église Saint-Jean-Baptiste',
    verzeichnispfad: 'Saint-Jean-Baptiste',
    beitragtitel: 'Prädikat: «Mérite un détour»',
    ort: 'Gland',
    bild: 'gland-saint-jean-baptiste/Bild1.jpeg',
    autor: 'David Zimmer',
    jahr: '2022',
    markierungen: [[46.42244, 6.26538]],
    kanton: Kantone.Waadt,
  },
/*
  'Basel Galluspforte': {
    karusselltitel: 'Die Galluspforte am Basler Münster',
    verzeichnispfad: 'Die Galluspforte am Basler Münster',
    beitragtitel: 'Die Galluspforte am Basler Münster',
    ort: 'Basel',
    bild: 'basel-galluspforte/Bild0.jpeg',
    autor: 'Silvan Beer',
    jahr: '2022',
    markierungen: [[47.55621, 7.59225]],
    kanton: Kantone.BaselStadt,
  },*/

  'St. Mangen - Die älteste Kirche der Stadt St. Gallen': {
    karusselltitel: 'St. Mangen - Die älteste Kirche der Stadt St. Gallen',
    verzeichnispfad: 'St. Mangen - Die älteste Kirche der Stadt St. Gallen',
    beitragtitel: 'St. Mangen - Die älteste Kirche der Stadt St. Gallen',
    ort: 'St. Gallen',
    bild: 'st-mangen-wiborada/Bild1.jpeg',
    autor: 'Ann-Katrin Gässlein',
    jahr: '2022',
    markierungen: [[47.42775, 9.37616]],
    kanton: Kantone.SanktGallen,
  },

  'Wallfahrtskirche Mariä Himmelfahrt': {
    karusselltitel: 'Wallfahrtskirche Mariä Himmelfahrt',
    verzeichnispfad: 'Wallfahrtskirche Mariä Himmelfahrt',
    beitragtitel: 'Wallfahrtskirche Mariä Himmelfahrt in Oberdorf',
    ort: 'Oberdorf',
    bild: 'oberdorf-wallfahrtskirche/Bild1.jpg',
    autor: 'Peter Widmer',
    jahr: '2022',
    markierungen: [[47.2293, 7.503]],
    kanton: Kantone.Solothurn,
  },

  'Das Amphitheater Vindonissa': {
    karusselltitel: 'Das Amphitheater Vindonissa',
    verzeichnispfad: 'Das Amphitheater Vindonissa',
    beitragtitel: 'Vom Kultort zur Kulturstätte: Das Amphitheater Vindonissa',
    ort: 'Windisch',
    bild: 'windisch-das-amphitheater-vindonissa/bild1.jpg',
    autor: 'Tabea Stauffer',
    jahr: '2022',
    markierungen: [[47.47628, 8.21373]],
    kanton: Kantone.Aargau,
  },
  'Totentanz Basel': {
    karusselltitel: 'Totentanz',
    verzeichnispfad: 'Totentanz',
    beitragtitel: 'Vom tanzenden Tod ...',
    ort: 'Basel',
    bild: 'basel-totentanz/bild1.jpeg',
    autor: 'Michael Bangert',
    jahr: '2022',
    markierungen: [[47.56201, 7.58523]],
    kanton: Kantone.BaselStadt,
  },

  'Tempelland der Schweizer Bahai-Gemeinde': {
    karusselltitel: 'Tempelland der Schweizer Bahai-Gemeinde',
    verzeichnispfad: 'Tempelland der Schweizer Bahai-Gemeinde',
    beitragtitel: 'Haus der Andacht mit Blick auf die Berge',
    ort: 'Kirchenthurnen',
    bild: 'kirchenthurnen-bahai/bild1.jpg',
    autor: 'Ruth Merz',
    jahr: '2022',
    markierungen: [[46.8219, 7.5007]],
    kanton: Kantone.Bern,
  },

  'Kunstprojekt Cantus firmus': {
    karusselltitel: 'Kunstprojekt Cantus firmus',
    verzeichnispfad: 'Kunstprojekt Cantus firmus',
    beitragtitel:
      'Cantus firmus - Kommunikation zwischen Mikrokosmos und Makrokosmos',
    ort: 'Solothurn',
    bild: 'solothurn-cantus-firmus/bild5.jpeg',
    autor: 'Adriana Basso Schaub',
    jahr: '2022',
    markierungen: [[47.209, 7.53763]],
    kanton: Kantone.Solothurn,
  },
  'Die Soeurs grises von Solothurn': {
    karusselltitel: 'Die Sœurs grises von Solothurn',
    verzeichnispfad: 'Die Soeurs grises von Solothurn',
    beitragtitel:
      'Krankenpflege in der frühen Neuzeit - Die Sœurs grises von Solothurn',
    ort: 'Solothurn',
    bild: 'solothurn-soeurs-grises/bild2.jpeg',
    autor: 'Ulrike Münger',
    jahr: '2022',
    markierungen: [[47.20506, 7.53587]],
    kanton: Kantone.Solothurn,
  },

  'Poschiavo Friedhof Hildesheimers Grab': {
    karusselltitel: 'Friedhof Hildesheimers Grab',
    verzeichnispfad: 'Friedhof Hildesheimers Grab',
    beitragtitel: 'Auf den Spuren der Steinchen auf den Grabsteinen',
    ort: 'Poschiavo (GR)',
    bild: 'poschiavo-friedhof-hildesheimers-grab/bild4.jpeg',
    autor: 'Valérie Rhein',
    jahr: '2022',
    markierungen: [[46.32675, 10.0591]],
    kanton: Kantone.Graubünden,
  },
  'Kleinhöchstetten evangelisch-reformierte Kirche': {
    karusselltitel: 'Die evangelisch-reformierte Kirche',
    verzeichnispfad: 'Die evangelisch-reformierte Kirche',
    beitragtitel:
      'Ältester erhaltener frühromanischer Sakralbau im Bernbiet und Ausgangspunkt der Berner Reformation ',
    ort: 'Kleinhöchstetten (BE)',
    bild: 'kleinhoechstetten-kirche/bild0.jpeg',
    autor: 'Miriam Löhr',
    jahr: '2022',
    markierungen: [[46.90329, 7.53132]],
    kanton: Kantone.Bern,
  },
  'Rüegsau Reformierte Kirche': {
    karusselltitel: 'Reformierte Kirche',
    verzeichnispfad: 'Reformierte Kirche',
    beitragtitel: 'Reformierte Kirche Rüegsau',
    ort: 'Rüegsau (BE)',
    bild: 'rueegsau-kirche/bild1.jpg',
    autor: 'Rolf Weibel',
    jahr: '2021',
    markierungen: [[47.02472, 7.67451]],
    kanton: Kantone.Bern,
  },
  'Visp St. Martinskirche': {
    karusselltitel: 'St. Martinskirche Visp',
    verzeichnispfad: 'St. Martinskirche Visp',
    beitragtitel: 'Die St. Martinskirche Visp',
    ort: 'Visp (VS)',
    bild: 'visp-martinskirche/bild1.jpeg',
    autor: 'Damian Pfammatter',
    jahr: '2021',
    markierungen: [[46.28911, 7.88096]],
    kanton: Kantone.Wallis,
  },
  'Erlenbach Sankt Michaelskirche': {
    karusselltitel: 'Sankt Michaelskirche',
    verzeichnispfad: 'Sankt Michaelskirche',
    beitragtitel: 'Die Sankt Michaelskirche von Erlenbach im Simmental',
    ort: 'Erlenbach (BE)',
    bild: 'erlenbach-sankt-michaelskirche/bild2.jpeg',
    autor: 'Hans Hofer',
    jahr: '2021',
    markierungen: [[46.66085, 7.5519]],
    kanton: Kantone.Bern,
  },
  'Aletschgletscher Arme Seelen': {
    karusselltitel: 'Gletschersage',
    verzeichnispfad: 'Gletschersage',
    beitragtitel: 'Von den Armen Seelen im Gletscher',
    ort: 'Aletschgletscher (VS)',
    bild: 'aletschgletscher-arme-seelen/bild1.JPG',
    autor: 'Andreas Weissen',
    jahr: '2021',
    markierungen: [[46.39207, 8.0023]],
    kanton: Kantone.Wallis,
  },
  'Solothurn Spitalkirche': {
    karusselltitel: 'Spitalkirche',
    verzeichnispfad: 'Spitalkirche',
    beitragtitel: 'Spitalkirche zum Heiligen Geist in Solothurn',
    ort: 'Solothurn',
    bild: 'solothurn-spitalkirche/bild1.jpg',
    autor: 'Deborah Finger-Oppliger',
    jahr: '2021',
    markierungen: [[47.20506, 7.53587]],
    kanton: Kantone.Solothurn,
  },
  'Solothurn zwei Heilige': {
    karusselltitel: 'Solothurn Zwei Heilige',
    verzeichnispfad: 'Solothurn Zwei Heilige',
    beitragtitel: 'Zwei Heilige überblicken Solothurn',
    ort: 'Solothurn',
    bild: 'solothurn-zwei-heilige/bild1.jpg',
    autor: 'Joël Meier',
    jahr: '2021',
    markierungen: [[47.2083, 7.53934]],
    kanton: Kantone.Solothurn,
  },
  Filmpodium: {
    karusselltitel: 'Filmpodium',
    verzeichnispfad: 'Filmpodium',
    beitragtitel: 'C’est où, le Filmpodium?',
    bild: 'biel-filmpodium/bild1.jpg',
    ort: 'Biel (BE)',
    autor: 'Sina von Aesch',
    jahr: '2021',
    markierungen: [[47.1389, 7.2397]],
    kanton: Kantone.Bern,
  },
  'Weitblick und Enge': {
    karusselltitel: 'Weitblick und Enge',
    verzeichnispfad: 'Weitblick und Enge',
    beitragtitel: 'Weitblick und Enge im Luzerner Hinterland',
    ort: 'Sulzig/Werthenstein (LU)',
    bild: 'sulzig-weitblick/bild1.jpg',
    autor: 'Gregor Emmenegger, David Neuhold, Anton Schwingruber',
    jahr: '2021',
    markierungen: [[47.0445, 8.08993]],
    kanton: Kantone.Luzern,
  },
  'Basel Jüdisches Museum': {
    karusselltitel: 'Jüdisches Museum',
    verzeichnispfad: 'Jüdisches Museum',
    beitragtitel: 'Kulturhistorisches Schaufenster der jüdischen Schweiz',
    ort: 'Basel',
    bild: 'basel-juedisches-museum/bild3.jpg',
    autor: 'David Zimmer',
    jahr: '2021',
    markierungen: [
      [47.55652, 7.58335],
      [47.5576245, 7.5830794],
    ],
    kanton: Kantone.BaselStadt,
  },
  Klosterort: {
    karusselltitel: 'Klosterort',
    verzeichnispfad: 'Klosterort',
    beitragtitel: 'Mariastein, ein Wallfahrts- und Klosterort',
    bild: 'mariastein-klosterort/bild1.jpg',
    ort: 'Mariastein (SO)',
    autor: 'Pater Lukas Schenker',
    jahr: '2021',
    markierungen: [[47.47603, 7.49302]],
    kanton: Kantone.Solothurn,
  },
  Spreuerbrücke: {
    karusselltitel: 'Spreuerbrücke',
    verzeichnispfad: 'Spreuerbrücke',
    beitragtitel: 'Die Spreuerbrücke in Luzern',
    bild: 'luzern-spreuerbruecke/bild1.jpg',
    ort: 'Luzern',
    autor: 'Sina von Aesch',
    jahr: '2021',
    markierungen: [[47.05183, 8.30165]],
    kanton: Kantone.Luzern,
  },
  Benediktinerkloster: {
    karusselltitel: 'Benediktinerkloster',
    verzeichnispfad: 'Benediktinerkloster',
    beitragtitel: 'Benediktinerkloster Disentis',
    bild: 'disentis-benediktinerkloster/bild2.jpeg',
    ort: 'Disentis (GR)',
    autor: 'Jan Peter Lang',
    jahr: '2021',
    markierungen: [[46.7071, 8.8563]],
    kanton: Kantone.Graubünden,
  },

  'Simplon Hospiz': {
    karusselltitel: 'Simplon Hospiz',
    verzeichnispfad: 'Simplon Hospiz',
    beitragtitel: 'Simplon Hospiz',
    ort: 'Simplon Pass (VS)',
    bild: 'simplon-pass-hospiz/bild1.jpg',
    autor: 'Daniel Salzgeber',
    jahr: '2021',
    markierungen: [[46.2467, 8.0293]],
    kanton: Kantone.Wallis,
  },
  'Bern Ökumenische Kirche im Haus der Religionen': {
    karusselltitel: 'Ökumenische Kirche im Haus der Religionen',
    verzeichnispfad: 'Ökumenische Kirche im Haus der Religionen',
    beitragtitel: 'Ökumenische Kirche im Haus der Religionen',
    bild: 'bern-oekumenische-kirche-hdr/bild0.jpeg',
    ort: 'Bern',
    autor: 'Angela Büchel Sladkovic, Frieder Vollprecht, Christian Walti ',
    jahr: '2021',
    markierungen: [[46.94362, 7.40597]],
    kanton: Kantone.Bern,
  },
  'Berner Totentanz': {
    karusselltitel: 'Berner Totentanz',
    verzeichnispfad: 'Berner Totentanz',
    beitragtitel: 'Berner Totentanz',
    bild: 'bern-totentanz/bild1.jpg',
    ort: 'Bern',
    autor: 'Matthias D. Berger',
    jahr: '2021',
    markierungen: [[46.94895, 7.44642]],
    kanton: Kantone.Bern,
  },
  Verenaschlucht: {
    karusselltitel: 'Verenaschlucht',
    verzeichnispfad: 'Verenaschlucht',
    beitragtitel: 'Die Heilige Verena bei Solothurn',
    bild: 'ruettenen-verenaschlucht/bild1.jpg',
    ort: 'Rüttenen (SO)',
    autor: 'Raphael Hadorn',
    jahr: '2021',
    markierungen: [[47.2246, 7.534]],
    kanton: Kantone.Solothurn,
  },
  'Begegnungen in Bethlehem': {
    karusselltitel: 'Begegnungen in Bethlehem',
    verzeichnispfad: 'Begegnungen in Bethlehem',
    beitragtitel: 'Begegnungen in Bethlehem',
    bild: 'bethlehem-kirche/bernbetlehem.jpg',
    ort: 'Bethlehem (BE)',
    autor: 'Andreas Köhler-Andereggen',
    jahr: '2020',
    markierungen: [[46.9495, 7.3927]],
    kanton: Kantone.Bern,
  },
  Kapelle: {
    karusselltitel: 'Kapelle',
    verzeichnispfad: 'Kapelle',
    beitragtitel: 'Die Kapelle auf der Belalp/Lüsga',
    bild: 'belalp-kapelle/belalpKapelle.jpg',
    ort: 'Belalp (VS)',
    autor: 'Gerd Dönni',
    jahr: '2020',
    markierungen: [[46.3813, 7.99124]],
    kanton: Kantone.Wallis,
  },
  Kollegiumskirche: {
    karusselltitel: 'Kollegiumskirche',
    verzeichnispfad: 'Kollegiumskirche',
    beitragtitel: 'Die Kollegiumskirche zum Heiligen Geist in Brig',
    bild: 'brig-kollegiumskirche/bild2.jpg',
    ort: 'Brig (VS)',
    autor: 'Gerd Dönni',
    jahr: '2020',
    markierungen: [[46.3153, 7.99214]],
    kanton: Kantone.Wallis,
  },
  Kindlifresserbrunnen: {
    karusselltitel: 'Kindlifresserbrunnen',
    verzeichnispfad: 'Kindlifresserbrunnen',
    beitragtitel:
      'Von Kinderfressern und der Relevanz der Juden für die Christen',
    bild: 'bern-kindlifresser/bild1.jpg',
    ort: 'Bern',
    autor: 'René Bloch',
    jahr: '2020',
    markierungen: [[46.94849, 7.4475]],
    kanton: Kantone.Bern,
  },
  'Swiss Church in London': {
    karusselltitel: 'Swiss Church in London',
    verzeichnispfad: 'Swiss Church in London',
    beitragtitel: 'The Swiss Church in London',
    ort: 'London',
    bild: 'london-church/bild1.jpg',
    autor: 'Carla Maurer',
    jahr: '2020',
    markierungen: [[51.5154, -0.1262]],
    kanton: Kantone.London,
  },
  'Ehemaliges Burgerspital': {
    karusselltitel: 'Ehemaliges Burgerspital',
    verzeichnispfad: 'Ehemaliges Burgerspital',
    beitragtitel: 'Von goldenen Lettern und der Fremdheit ihrer Hoffnung',
    bild: 'bern-burgerspital/burgerspital2.jpeg',
    ort: 'Bern',
    autor: 'Matthias Käser',
    jahr: '2020',
    markierungen: [[46.94774, 7.4393]],
    kanton: Kantone.Bern,
  },
  'Amsoldingen Kirche': {
    karusselltitel: 'Amsoldingen Kirche',
    verzeichnispfad: 'Amsoldingen Kirche',
    beitragtitel: 'Die Kirche Amsoldingen – ein Juwel im Berner Oberland',
    bild: 'amsoldingen-kirche/amsoldingen.jpg',
    ort: 'Amsoldingen (BE)',
    autor: 'Nicole Hublard',
    jahr: '2021',
    markierungen: [[46.7272, 7.57891]],
    kanton: Kantone.Bern,
  },
  'Studium der Ostkirchen': {
    karusselltitel: 'Studium der Ostkirchen',
    verzeichnispfad: 'Studium der Ostkirchen',
    beitragtitel:
      'Zentrum für das Studium der Ostkirchen an der Universität Freiburg: Orthodoxe Spiritualität in einer Universität katholischer Prägung',
    bild: 'freiburg-zentrum/bild3.jpg',
    ort: 'Freiburg',
    autor: 'Stefan Constantinescu',
    jahr: '2020',
    markierungen: [[46.80643, 7.15137]],
    kanton: Kantone.Fribourg,
  },
  'Études des Églises d’Orient': {
    karusselltitel: 'Centre d’études des Églises d’Orient',
    verzeichnispfad: 'Etudes des Eglises dOrient',
    beitragtitel:
      'Centre d’études des Églises d’Orient à l’Université de Fribourg: La spiritualité orthodoxe dans une université à caractère catholique',
    bild: 'freiburg-centre-dorient/bild3.jpg',
    ort: 'Freiburg',
    autor: 'Stefan Constantinescu',
    jahr: '2020',
    markierungen: [[46.80643, 7.15137]],
    kanton: Kantone.Fribourg,
  },
  'Antoniterkirche Antonius-Fresken': {
    karusselltitel: 'Antoniterkirche Antonius-Fresken',
    verzeichnispfad: 'Antoniterkirche Antonius-Fresken',
    beitragtitel:
      'Die Antonius-Fresken von Fritz Pauli – ein reformiertes Bildprogramm',
    bild: 'bern-antoniterkirche-antonius-fresken/antonbild3.jpg',
    ort: 'Bern',
    autor: 'Katharina Heyden',
    jahr: '2020',
    markierungen: [[46.94895, 7.45359]],
    kanton: Kantone.Bern,
  },
  'Kraftwerk Birsfelden': {
    karusselltitel: 'Kraftwerk Birsfelden',
    verzeichnispfad: 'Kraftwerk Birsfelden',
    beitragtitel:
      'Das Kraftwerk Birsfelden – ein theologischer Erinnerungsort?',
    bild: 'birsfelden-kraftwerk/bild1.jpg',
    ort: 'Birsfelden (BL)',
    autor: 'Georg Kreis',
    jahr: '2020',
    markierungen: [[47.5605, 7.6259]],
    kanton: Kantone.BaselLand,
  },
  'Stationenweg zur Täufergeschichte': {
    karusselltitel: 'Stationenweg zur Täufergeschichte',
    verzeichnispfad: 'Stationenweg zur Täufergeschichte',
    beitragtitel: 'Stationenweg zur Täufergeschichte',
    bild: 'bern-taeufergeschichte/bild2.jpg',
    ort: 'Bern',
    autor: 'Dorothea Loosli-Amstutz',
    jahr: '2020',
    markierungen: [[46.94742, 7.45157]],
    kanton: Kantone.Bern,
  },
  'Dürrenmatts Mansarde': {
    karusselltitel: 'Dürrenmatts Mansarde',
    verzeichnispfad: 'Dürrenmatts Mansarde',
    beitragtitel: 'Dürrenmatts Mansarde',
    bild: 'bern-duerrenmatt-mansarde/bild2.jpg',
    ort: 'Bern',
    autor: 'Christoph Morgenthaler',
    jahr: '2020',
    markierungen: [[46.94872, 7.46459]],
    kanton: Kantone.Bern,
  },
  'Münster Portal': {
    karusselltitel: 'Münster Portal',
    verzeichnispfad: 'Münster Portal',
    beitragtitel:
      'Vom Wiegen des Herzens und Feuerseen – Altägyptische Unterweltsvorstellungen am Portal des Berner Münsters?',
    bild: 'bern-muenster-portal/bild1.jpg',
    ort: 'Bern',
    autor: 'Ulrike Münger',
    jahr: '2019',
    markierungen: [[46.94723, 7.45134]],
    kanton: Kantone.Bern,
  },
  'Hebammenpforte des Berner Münsters': {
    karusselltitel: 'Hebammenpforte des Berner Münsters',
    verzeichnispfad: 'Hebammenpforte des Berner Münsters',
    beitragtitel: 'Hebammenpforte des Berner Münsters',
    bild: 'bern-hebammenpforte/bild1.jpg',
    ort: 'Bern',
    autor: 'Adrienne Shannon Grossenbacher',
    jahr: '2019',
    markierungen: [[46.94741, 7.45157]],
    kanton: Kantone.Bern,
  },
  'Martinskirche Rüeggisberg': {
    karusselltitel: 'Martinskirche Rüeggisberg',
    verzeichnispfad: 'Martinskirche Rüeggisberg',
    beitragtitel: 'Martinskirche Rüeggisberg',
    bild: 'rueggisberg-martinskirche/bild3.jpg',
    ort: 'Rüeggisberg (BE)',
    autor: 'Elisabeth Willen-Lanzrein',
    jahr: '2019',
    markierungen: [[46.8215, 7.4387]],
    kanton: Kantone.Bern,
  },
  'Ökumenisches Institut': {
    karusselltitel: 'Ökumenisches Institut',
    verzeichnispfad: 'Ökumenisches Institut',
    beitragtitel:
      'Ökumenisches Institut Bossey – einzigartiges Laboratorium der ökumenischen Bewegung',
    bild: 'bossey-institut/bild1.jpg',
    ort: 'Bogis-Bossey (VD)',
    autor: 'David Zimmer',
    jahr: '2019',
    markierungen: [[46.34756, 6.18565]],
    kanton: Kantone.Waadt,
  },
  'Der Heilige Vinzenz als Kirchenpatron des Berner Münsters': {
    karusselltitel: 'Münster St. Vinzenz',
    verzeichnispfad: 'Münster St. Vinzenz',
    beitragtitel: 'Der Heilige Vinzenz als Kirchenpatron des Berner Münsters',
    bild: 'bern-muenster-vinzenz/bild1.jpg',
    ort: 'Bern',
    autor: 'Alexandra Kreyden',
    jahr: '2019',
    markierungen: [[46.94743, 7.45157]],
    kanton: Kantone.Bern,
  },
  Gnadenbrunnen: {
    karusselltitel: 'Gnadenbrunnen',
    verzeichnispfad: 'Gnadenbrunnen',
    beitragtitel: 'Das Wunderwasser der Luzerner Bauern',
    bild: 'luthernbad-gnadenbrunnen/bild1.jpg',
    ort: 'Luthernbad (LU)',
    autor: 'Hans Herrmann',
    jahr: '2019',
    markierungen: [[47.02541, 7.92512]],
    kanton: Kantone.Luzern,
  },
  'Scherzligen Kirche': {
    karusselltitel: 'Scherzligen Kirche',
    verzeichnispfad: 'Scherzligen Kirche',
    beitragtitel: '«Early Adopter» am Ausfluss des Thunersees',
    bild: 'scherzligen-kirche/bild1.jpg',
    ort: 'Thun (BE)',
    autor: 'Markus Nägeli',
    jahr: '2019',
    markierungen: [[46.74735, 7.63631]],
    kanton: Kantone.Bern,
  },
  'Hindelbank Kirche': {
    karusselltitel: 'Hindelbank Kirche',
    verzeichnispfad: 'Hindelbank Kirche',
    beitragtitel: 'Die Kraft der Auferstehung in Stein gemeisselt',
    bild: 'hindelbank-kirche/bild1.jpg',
    ort: 'Hindelbank (BE)',
    autor: 'Hans Herrmann',
    jahr: '2019',
    markierungen: [[47.04184, 7.54023]],
    kanton: Kantone.Bern,
  },
  Vincentiustafel: {
    karusselltitel: 'Vincentiustafel',
    verzeichnispfad: 'Vincentiustafel',
    beitragtitel:
      'Von Engeln getragen. Der Märtyrer Vincentius von Saragossa im Basler Münster',
    bild: 'basel-vincentiustafel/vincentiustafel.jpg',
    ort: 'Basel',
    autor: 'Maria Lissek',
    jahr: '2018',
    markierungen: [[47.5565, 7.5925]],
    kanton: Kantone.BaselStadt,
  },
  'Cigognier-Heiligtum': {
    karusselltitel: 'Cigognier-Heiligtum',
    verzeichnispfad: 'Cigognier-Heiligtum',
    beitragtitel: 'Das Cigognier-Heiligtum und der Kaiserkult',
    bild: 'avenches-cigognier-heiligtum/avenches.jpg',
    ort: 'Avenches (VD)',
    autor: 'Sara Egger',
    jahr: '2018',
    markierungen: [[46.881, 7.04265]],
    kanton: Kantone.Waadt,
  },
  'Riva San Vitale Baptisterium': {
    karusselltitel: 'San Vitale Baptisterium',
    verzeichnispfad: 'San Vitale Baptisterium',
    beitragtitel:
      'Baptisterien aus dem 5. und 6. Jahrhundert in der heutigen Schweiz',
    ort: 'Riva San Vitale (TI)',
    bild: 'riva-san-vitale-baptisterium/bild0.jpeg',
    autor: 'Maria Lissek',
    jahr: '2016',
    markierungen: [
      [47.58543, 8.30062],
      [45.90469, 8.97095],
      [46.2197, 7.00367],
    ],
    kanton: Kantone.Tessin,
  },
  Feder: {
    karusselltitel: 'Feder',
    verzeichnispfad: 'Feder',
    beitragtitel: 'Eine bewegende Feder als Wallfahrtsziel?',
    bild: 'bueren-feder/bild1.jpg',
    ort: 'Büren an der Aare (BE)',
    autor: 'Dominik von Allmen',
    jahr: '2016',
    markierungen: [[47.13749, 7.38003]],
    kanton: Kantone.Bern,
  },
  'Synagogen und Friedhof': {
    karusselltitel: 'Synagogen und Friedhof',
    verzeichnispfad: 'Synagogen und Friedhof',
    beitragtitel: 'Der «gute Ort», ein Haus für die Ewigkeit',
    bild: 'endingen-friedhof/bild2.jpg',
    ort: 'Endingen (AG)',
    autor: 'René Bloch',
    jahr: '2016',
    markierungen: [[47.5332, 8.3089]],
    kanton: Kantone.Aargau,
  },
  'Saint Maurice Baptisterium': {
    karusselltitel: 'Saint Maurice Baptisterium',
    verzeichnispfad: 'Saint Maurice Baptisterium',
    beitragtitel:
      'Baptisterien aus dem 5. und 6. Jahrhundert in der heutigen Schweiz',
    ort: 'Saint Maurice (VS)',
    bild: 'saint-maurice-baptisterium/bild0.jpeg',
    autor: 'Maria Lissek',
    jahr: '2016',
    markierungen: [
      [47.58543, 8.30062],
      [45.90469, 8.97095],
      [46.2197, 7.00367],
    ],
    kanton: Kantone.Tessin,
  },
  Abbatiale: {
    karusselltitel: 'L’abbatiale de Bellelay',
    verzeichnispfad: 'Abbatiale',
    beitragtitel:
      'L’abbatiale de Bellelay – échos du passé et musique d’avenir',
    bild: 'bellelay-abbatiale/abbatiale.jpg',
    ort: 'Bellelay (BE)',
    autor: 'Lara A. Kneubühler',
    jahr: '2016',
    markierungen: [[47.26409, 7.16869]],
    kanton: Kantone.Bern,
  },
  'Zentrum Paul Klee': {
    karusselltitel: 'Zentrum Paul Klee',
    verzeichnispfad: 'Zentrum Paul Klee',
    beitragtitel: 'Ein Ort für Transzendenzerfahrungen?',
    bild: 'bern-paul-klee/bild1.jpg',
    ort: 'Bern',
    autor: 'Magdalene L. Frettlöh',
    jahr: '2016',
    markierungen: [[46.94907, 7.47429]],
    kanton: Kantone.Bern,
  },
  Baptisterium: {
    karusselltitel: 'Baptisterium',
    verzeichnispfad: 'Baptisterium',
    beitragtitel:
      'Baptisterien aus dem 5. und 6. Jahrhundert in der heutigen Schweiz',
    bild: 'badzurzach-baptisterium/bad_zurzach_baptisterium.jpg',
    ort: 'Bad Zurzach (AG)',
    autor: 'Maria Lissek',
    jahr: '2016',
    markierungen: [
      [47.58543, 8.30062],
      [45.90469, 8.97095],
      [46.2197, 7.00367],
    ],
    kanton: Kantone.Aargau,
  },
  'Kirche St.Martin': {
    karusselltitel: 'Kirche St.Martin',
    verzeichnispfad: 'Kirche St.Martin',
    beitragtitel:
      'Spuren eines vielfachen Erinnerungsträgers – Martin von Tours und seine Kultorte',
    bild: 'basel-martinskirche/bild1.jpg',
    ort: 'Basel',
    autor: 'Angela Berlis',
    jahr: '2016',
    markierungen: [
      [47.55907, 7.58861],
      [47.53123, 7.8109],
      [46.63449, 9.44162],
    ],
    kanton: Kantone.BaselStadt,
  },
  Antoniterkirche: {
    karusselltitel: 'Antoniterkirche',
    verzeichnispfad: 'Antoniterkirche',
    beitragtitel:
      'Himmel, Erde, West und Ost – Die Antoniterkirche in der Berner Altstadt',
    bild: 'bern-antoniterkirche/antoniterkirche_heimlich.jpg',
    ort: 'Bern',
    autor: 'Nadja Heimlicher',
    jahr: '2016',
    markierungen: [[46.94895, 7.45359]],
    kanton: Kantone.Bern,
  },
  'Haus der Religionen': {
    karusselltitel: 'Haus der Religionen',
    verzeichnispfad: 'Haus der Religionen',
    beitragtitel: 'Haus der Religionen: Das Mit- und Nebeneinander gestalten',
    bild: 'bern-haus-der-religionen/bild1.jpg',
    ort: 'Bern',
    autor: 'Anna-Konstanze Schröder',
    jahr: '2016',
    markierungen: [[46.94362, 7.40597]],
    kanton: Kantone.Bern,
  },
  'Schloss Gottlieben': {
    karusselltitel: 'Schloss Gottlieben',
    verzeichnispfad: 'Schloss Gottlieben',
    beitragtitel: 'Gefängnis des Reformators Jan Hus',
    bild: 'gottlieben-schloss/bild1.jpg',
    ort: 'Gottlieben (TG)',
    autor: 'Zbynek Kindschi Garsky',
    jahr: '2016',
    markierungen: [[47.66405, 9.13602]],
    kanton: Kantone.Thurgau,
  },
  'Maennedorf Zentrum der Heiligungsbewegung': {
    karusselltitel: 'Zentrum der Heiligungsbewegung',
    verzeichnispfad: 'Zentrum der Heiligungsbewegung',
    beitragtitel: 'Zentrum der Heiligungsbewegung',
    bild: 'maennedorf-zentrum-der-heiligungsbewegung/bild1.jpg',
    ort: 'Männedorf (ZH)',
    autor: 'Gergely Csukás',
    jahr: '2016',
    markierungen: [[47.25591, 8.69311]],
    kanton: Kantone.Zürich,
  },
  'Stiftskirche St. Leodegar': {
    karusselltitel: 'Stiftskirche St. Leodegar',
    verzeichnispfad: 'Stiftskirche St. Leodegar',
    beitragtitel: 'Zwischen Marienwallfahrt und Kulturkampf',
    ort: 'Schönenwerd (SO)',
    bild: 'schoenenwerd-stiftskirche/bild1.jpg',
    autor: 'Adrian Suter',
    jahr: '2016',
    markierungen: [[47.37193, 8.00439]],
    kanton: Kantone.Solothurn,
  },
  'Restaurant Blinde Kuh': {
    karusselltitel: 'Restaurant Blinde Kuh',
    verzeichnispfad: 'Restaurant Blinde Kuh',
    beitragtitel: 'Blinde Kuh – mehr als ein Restaurant',
    ort: 'Zürich',
    bild: 'zuerich-blindekuh/bild1.jpg',
    autor: 'Christoph Sigrist',
    jahr: '2016',
    markierungen: [[47.35834, 8.55719]],
    kanton: Kantone.Zürich,
  },
  'Schwarze Madonna': {
    karusselltitel: 'Schwarze Madonna',
    verzeichnispfad: 'Schwarze Madonna',
    beitragtitel: 'Wenn die «heilige Kranke» zur schwarzen Madonna geht...',
    bild: 'einsiedeln-madonna/bild1.jpg',
    ort: 'Einsiedeln (SZ)',
    autor: 'Ulrike Münger',
    jahr: '2015',
    markierungen: [[47.1267, 8.7523]],
    kanton: Kantone.Schwyz,
  },
};
