import { Kantone } from 'src/app/components/models/kantone';

export const Beiträge = {
  /*


    'Die Marienkirche – Zeugin der bewegten Geschichte der römisch-katholischen Pfarrei Davos':
    {
      karusselltitel:
        'Die Marienkirche – Zeugin der bewegten Geschichte der römisch-katholischen Pfarrei Davos',
      verzeichnispfad: 'marienkirche',
      beitragtitel:
        'Die Marienkirche – Zeugin der bewegten Geschichte der römisch-katholischen Pfarrei Davos',
      ort: 'Davos (GR)',
      bild: 'davos-marienkirche/bild0.jpeg',
      autor: 'Petra Homberger',
      jahr: '2024',
      markierungen: [[46.79531, 9.81833]],
      kanton: Kantone.Graubünden,
    },


'Mitten in Zürich - wo man seine Spiritualität kunstvoll entfalten kann': {
    karusselltitel:
      'Mitten in Zürich - wo man seine Spiritualität kunstvoll entfalten kann',
    verzeichnispfad: 'herzjesuwiedikon',
    beitragtitel:
      'Mitten in Zürich - wo man seine Spiritualität kunstvoll entfalten kann',
    ort: 'Zürich',
    bild: 'zuerich-herzjesu/bild0.jpeg',
    autor: 'Silke Weinig',
    jahr: '2024',
    markierungen: [[47.37271, 8.51431]],
    kanton: Kantone.Zürich,
  },







  

*/

  'Im Tal des Lichts': {
    karusselltitel: 'Im Tal des Lichts',
    verzeichnispfad: 'taldeslichts',
    beitragtitel: 'Pleif – Im Tal des Lichts',
    ort: 'Pleif',
    bild: 'pleif-taldeslichts/bild1.jpeg',
    autor: 'Ralph Kunz',
    jahr: '2024',
    markierungen: [[46.71519, 9.17901]],
    kanton: Kantone.Graubünden,
  },

  'Das Refugium des Zweiflers: Das Centre Dürrenmatt': {
    karusselltitel: 'Das Refugium des Zweiflers: Das Centre Dürrenmatt',
    verzeichnispfad: 'cdn',
    beitragtitel: 'Das Refugium des Zweiflers: Das Centre Dürrenmatt Neuchâtel',
    ort: 'Neuenburg/Neuchâtel',
    bild: 'neuenburg-cdn/bild1.jpeg',
    autor: 'Matthias Zeindler',
    jahr: '2024',
    markierungen: [[47.00123, 6.9365]],
    kanton: Kantone.Neuenburg,
  },

  'Bruderholzallee 26 – Adresse eines theologischen Denkabenteuers': {
    karusselltitel:
      'Bruderholzallee 26 – Adresse eines theologischen Denkabenteuers',
    verzeichnispfad: 'bruderholzallee',
    beitragtitel:
      'Bruderholzallee 26 – Adresse eines theologischen Denkabenteuers',
    ort: 'Basel',
    bild: 'basel-bruderholzallee/bild1.jpeg',
    autor: 'Albrecht Grözinger',
    jahr: '2024',
    markierungen: [[47.53457, 7.58727]],
    kanton: Kantone.BaselStadt,
  },

  'Der Wartesaal im Bieler Bahnhof – la salle d`attente': {
    karusselltitel: 'Der Wartesaal im Bieler Bahnhof – la salle d`attente',
    verzeichnispfad: 'wartesaal',
    beitragtitel: 'Der Wartesaal im Bieler Bahnhof – la salle d`attente',
    ort: 'Biel (BE)',
    bild: 'biel-wartesaal/bild2.jpeg',
    autor: 'Martina Schwarz',
    jahr: '2024',
    markierungen: [[46.13294, 7.24288]],
    kanton: Kantone.Bern,
  },

  'Kultur trifft Natur': {
    karusselltitel: 'Kultur trifft Natur',
    verzeichnispfad: 'schwarzwasser',
    beitragtitel: 'Rüschegg – Kultur trifft Natur',
    ort: 'Rüschegg (BE)',
    bild: 'rueschegg-schwarzwasser/bild1.jpeg',
    autor: 'Andreas Köhler-Andereggen',
    jahr: '2024',
    markierungen: [[46.77996, 7.39283]],
    kanton: Kantone.Bern,
  },

  'Der Gemmipass – Ein Weg durch die Jahrhunderte': {
    karusselltitel: 'Der Gemmipass – Ein Weg durch die Jahrhunderte',
    verzeichnispfad: 'gemmipass',
    beitragtitel: 'Der Gemmipass – Ein Weg durch die Jahrhunderte',
    ort: 'Leukerbad (VS)',
    bild: 'leukerbad-gemmipass/bild1.jpeg',
    autor: 'Miriam Löhr',
    jahr: '2024',
    markierungen: [[46.39631, 7.61142]],
    kanton: Kantone.Wallis,
  },

  'Interlaken – Ein Fremdenverkehrsort auf klösterlichem Boden gewachsen': {
    karusselltitel: 'Ein Fremdenverkehrsort auf klösterlichem Boden gewachsen',
    verzeichnispfad: 'jungfrau',
    beitragtitel:
      'Interlaken – Ein Fremdenverkehrsort auf klösterlichem Boden gewachsen',
    ort: 'Interlaken (BE)',
    bild: 'interlaken-kloster/bild0.jpeg',
    autor: 'Manuel von Däniken',
    jahr: '2024',
    markierungen: [[46.6875, 7.86439]],
    kanton: Kantone.Bern,
  },

  'Vom Kloster zum Museum, Historisches Museum Basel': {
    karusselltitel: 'Vom Kloster zum Museum, Historisches Museum Basel',
    verzeichnispfad: 'histmuseum',
    beitragtitel: 'Vom Kloster zum Museum, Historisches Museum Basel',
    ort: 'Basel',
    bild: 'basel-histmuseum/bild0.jpeg',
    autor: 'Elisheba Schmid',
    jahr: '2024',
    markierungen: [[47.55453, 7.59042]],
    kanton: Kantone.BaselStadt,
  },

  '«Nackte Füsse» in über 1000 Metern Höhe – der Waltensburger Meister und die von ihm erzählte Passion Christi':
    {
      karusselltitel:
        '«Nackte Füsse» in über 1000 Metern Höhe – der Waltensburger Meister und die von ihm erzählte Passion Christi',
      verzeichnispfad: 'passion',
      beitragtitel:
        'Waltensburg/Vuorz: «Nackte Füsse» in über 1000 Metern Höhe – der Waltensburger Meister und die von ihm erzählte Passion Christi',
      ort: 'Waltensburg/Vuorz (GR)',
      bild: 'waltensburg-passion/bild0.jpeg',
      autor: 'David Neuhold',
      jahr: '2024',
      markierungen: [[46.77711, 9.11758]],
      kanton: Kantone.Graubünden,
    },

  '«Schauplatz Brunngasse» Einvernehmliches Zusammenleben und katastrophaler Absturz – Jüdisches Leben im mittelalterlichen Zürich':
    {
      karusselltitel:
        '«Schauplatz Brunngasse» Einvernehmliches Zusammenleben und katastrophaler Absturz – Jüdisches Leben im mittelalterlichen Zürich',
      verzeichnispfad: 'brunngasse',
      beitragtitel:
        '«Schauplatz Brunngasse» Einvernehmliches Zusammenleben und katastrophaler Absturz – Jüdisches Leben im mittelalterlichen Zürich',
      ort: 'Zürich',
      bild: 'zuerich-brunngasse/bild0.jpeg',
      autor: 'Dölf Wild',
      jahr: '2024',
      markierungen: [[47.37314, 8.54453]],
      kanton: Kantone.Zürich,
    },

  'Stadtkirche Glarus - Das Simultaneum in Glarus': {
    karusselltitel: 'Stadtkirche Glarus - Das Simultaneum in Glarus',
    verzeichnispfad: 'simultaneum',
    beitragtitel: 'Stadtkirche Glarus - Das Simultaneum in Glarus',
    ort: 'Glarus',
    bild: 'glarus-simultaneum/bild0.jpeg',
    autor: 'Tamara Landolt',
    jahr: '2024',
    markierungen: [[47.04026, 9.06541]],
    kanton: Kantone.Glarus,
  },

  'Das Zisterzienserinnenkloster Tänikon': {
    karusselltitel: 'Das Zisterzienserinnenkloster Tänikon',
    verzeichnispfad: 'klostertaenikon',
    beitragtitel: 'Das Zisterzienserinnenkloster Tänikon',
    ort: 'Tänikon (TG)',
    bild: 'taenikon-kloster/bild0.jpeg',
    autor: 'Martin Brunner',
    jahr: '2024',
    markierungen: [[47.47942, 8.90724]],
    kanton: Kantone.Thurgau,
  },

  'Auch ich war hier! Adrian von Bubenberg in Jerusalem': {
    karusselltitel: 'Auch ich war hier! Adrian von Bubenberg in Jerusalem',
    verzeichnispfad: 'bubenberg',
    beitragtitel:
      'Der Abendmahlssaal auf dem Zionsberg in Jerusalem und sein Besucher Adrian von Bubenberg',
    ort: 'Jerusalem',
    bild: 'jerusalem-bubenberg/bild1.jpeg',
    autor: 'Jürgen Krüger',
    jahr: '2024',
    markierungen: [[31.77195, 35.2293]],
    kanton: Kantone.Jerusalem,
  },

  'Wer zum Schwert greift – Über die vier kleinen Männer am Berner Gerechtigkeitsbrunnen':
    {
      karusselltitel:
        'Wer zum Schwert greift – Über die vier kleinen Männer am Berner Gerechtigkeitsbrunnen',
      verzeichnispfad: 'gerechtigkeitsbrunnen',
      beitragtitel:
        'Wer zum Schwert greift – Über die vier kleinen Männer am Berner Gerechtigkeitsbrunnen',
      ort: 'Bern',
      bild: 'bern-gerechtigkeitsbrunnen/bild0.jpeg',
      autor: 'Torben Hanhart',
      jahr: '2024',
      markierungen: [[46.94828, 7.45407]],
      kanton: Kantone.Bern,
    },

  'Der Notker Globus und das mittelalterliche Weltbild': {
    karusselltitel: 'Der Notker Globus und das mittelalterliche Weltbild',
    verzeichnispfad: 'notkerglobus',
    beitragtitel:
      'St. Gallen: Der Notker Globus und das mittelalterliche Weltbild',
    ort: 'St. Gallen',
    bild: 'stgallen-notkerglobus/bild0.jpeg',
    autor: 'Sophie Strauch',
    jahr: '2024',
    markierungen: [[47.42266, 9.37697]],
    kanton: Kantone.SanktGallen,
  },

  'Spätantike Tradition und Moderne Kunst – Zwei Welten in der römisch-katholischen Kirche Oberwil':
    {
      karusselltitel:
        'Spätantike Tradition und Moderne Kunst – Zwei Welten in der römisch-katholischen Kirche Oberwil',
      verzeichnispfad: 'hansarp',
      beitragtitel:
        'Spätantike Tradition und Moderne Kunst – Zwei Welten in der römisch-katholischen Kirche Oberwil',
      ort: 'Oberwil (BL)',
      bild: 'oberwil-hansarp/bild0.jpeg',
      autor: 'Jonas Engeler',
      jahr: '2024',
      markierungen: [[47.51368, 7.55387]],
      kanton: Kantone.BaselLand,
    },

  'Der Campus Muristalden in Bern - Neues auf alten Pfaden begehen': {
    karusselltitel:
      'Der Campus Muristalden in Bern - Neues auf alten Pfaden begehen',
    verzeichnispfad: 'muristalden',
    beitragtitel:
      'Der Campus Muristalden in Bern - Neues auf alten Pfaden begehen',
    ort: 'Bern',
    bild: 'bern-muristalden/bild0.jpeg',
    autor: 'Meriel Lannutti',
    jahr: '2024',
    markierungen: [[46.94423, 7.45996]],
    kanton: Kantone.Bern,
  },

  'Taubenschlag und Davidstern – im Schatten der Marienkirche': {
    karusselltitel:
      'Taubenschlag und Davidstern – im Schatten der Marienkirche',
    verzeichnispfad: 'waschhaus',
    beitragtitel:
      'Basel: Taubenschlag und Davidstern – im Schatten der Marienkirche',
    ort: 'Basel',
    bild: 'basel-waschhaus/bild0.jpeg',
    autor: 'Patrick Braun',
    jahr: '2023',
    markierungen: [[47.55358, 7.58365]],
    kanton: Kantone.BaselStadt,
  },

  'Apollonia – Heilige mit Zange und Zahn': {
    karusselltitel: 'Apollonia – Heilige mit Zange und Zahn',
    verzeichnispfad: 'apollonia',
    beitragtitel: 'Alpthal (SZ): Apollonia – Heilige mit Zange und Zahn',
    ort: 'Alpthal (SZ)',
    bild: 'alpthal-apollonia/bild0.jpeg',
    autor: 'Katja Bury und Christoph Kerwien',
    jahr: '2023',
    markierungen: [[47.07077, 8.71608]],
    kanton: Kantone.Schwyz,
  },

  'Im Schatten des Kühlturms. Religiös vielfältige Sakrallandschaft im südlichen Niederamt':
    {
      karusselltitel:
        'Im Schatten des Kühlturms. Religiös vielfältige Sakrallandschaft im südlichen Niederamt',
      verzeichnispfad: 'niederamt',
      beitragtitel:
        'Im Schatten des Kühlturms. Religiös vielfältige Sakrallandschaft im südlichen Niederamt',
      ort: 'Niederamt (SO)',
      bild: 'niederamt-sakrallandschaft/bild0.jpg',
      autor: 'David Zimmer',
      jahr: '2023',
      markierungen: [
        [47.3563, 7.9787],
        [47.3713, 8.0003],
        [47.3592, 7.9936],
      ],
      kanton: Kantone.Solothurn,
    },

  'Das Epitaph des Erasmus von Rotterdam – Die Basler Hommage an den katholischen Humanisten':
    {
      karusselltitel:
        'Das Epitaph des Erasmus von Rotterdam – Die Basler Hommage an den katholischen Humanisten',
      verzeichnispfad: 'erasmusvonrotterdam',
      beitragtitel:
        'Das Epitaph des Erasmus von Rotterdam – Die Basler Hommage an den katholischen Humanisten',
      ort: 'Basel',
      bild: 'basel-erasmusvonrotterdam/Bild0.jpeg',
      autor: 'Andrea Flückiger',
      jahr: '2023',
      markierungen: [[47.55653, 7.59225]],
      kanton: Kantone.BaselStadt,
    },

  'Sant´Ambrogio vecchio in Prugiasco (San Carlo di Negrentino)': {
    karusselltitel: 'Sant´Ambrogio vecchio (San Carlo di Negrentino)',
    verzeichnispfad: 'santambrogio',
    beitragtitel: 'Prugiasco: Sant´Ambrogio vecchio (San Carlo di Negrentino)',
    ort: 'Prugiasco (TI)',
    bild: 'prugiasco-santambrogio/bild0.jpeg',
    autor: 'Jonathan Stutz',
    jahr: '2023',
    markierungen: [[46.46269, 8.92285]],
    kanton: Kantone.Tessin,
  },

  'Marienkirche – Kirchenbau in der Zeit des Kulturkampfs': {
    karusselltitel: 'Marienkirche – Kirchenbau in der Zeit des Kulturkampfs',
    verzeichnispfad: 'marienkirche',
    beitragtitel:
      'Basel: Marienkirche – Kirchenbau in der Zeit des Kulturkampfs',
    ort: 'Basel',
    bild: 'basel-marienkirche/bild0.jpeg',
    autor: 'Patrick Braun',
    jahr: '2023',
    markierungen: [[47.55349, 7.58417]],
    kanton: Kantone.BaselStadt,
  },

  'St. Gallen: Einmal einmauern, bitte.': {
    karusselltitel: 'Einmal einmauern, bitte.',
    verzeichnispfad: 'einmauern',
    beitragtitel:
      'St. Gallen: Einmal einmauern, bitte. Wie 1000 Jahre später der Heiligen Wiborada in St. Gallen nachgelebt wird.',
    ort: 'St. Gallen',
    bild: 'st-gallen-wiborada/Bild0.jpeg',
    autor: 'Andrea Mösching',
    jahr: '2023',
    markierungen: [[47.42775, 9.37616]],
    kanton: Kantone.SanktGallen,
  },

  'Die Schweizer Garde – ein bedeutsamer Ort der Schweiz?': {
    karusselltitel: 'Die Schweizer Garde – ein bedeutsamer Ort der Schweiz?',
    verzeichnispfad: 'schweizergarde',
    beitragtitel: 'Die Schweizer Garde – ein bedeutsamer Ort der Schweiz?',
    ort: 'Vatikan (I)',
    bild: 'vatikan-garde/Bild0.jpeg',
    autor: 'Tabea Stauffer',
    jahr: '2023',
    markierungen: [[41.90367, 12.45704]],
    kanton: Kantone.Vatikan,
  },

  'Der Lindenberg – Wiege von Katholisch-Basel': {
    karusselltitel: 'Der Lindenberg – Wiege von Katholisch-Basel',
    verzeichnispfad: 'lindenberg',
    beitragtitel: 'Der Lindenberg – Wiege von Katholisch-Basel',
    ort: 'Basel',
    bild: 'basel-lindenberg/Bild0.jpeg',
    autor: 'Patrick Braun',
    jahr: '2023',
    markierungen: [[47.55877, 7.59486]],
    kanton: Kantone.BaselStadt,
  },

  'Das Gotthelf Zentrum Emmental in Lützelflüh': {
    karusselltitel: 'Das Gotthelf Zentrum Emmental in Lützelflüh',
    verzeichnispfad: 'gotthelf',
    beitragtitel: 'Das Gotthelf Zentrum Emmental in Lützelflüh',
    ort: 'Lützelflüh (BE)',
    bild: 'luetzelflue-gotthelfzentrum/Bild0.jpeg',
    autor: 'Daniel N. Herrmann',
    jahr: '2023',
    markierungen: [[47.00881, 7.68739]],
    kanton: Kantone.Bern,
  },

  'Das Epitaph des Erasmus von Rotterdam im Basler Münster': {
    karusselltitel: 'Das Epitaph des Erasmus von Rotterdam im Basler Münster',
    verzeichnispfad: 'erasmus',
    beitragtitel: 'Das Epitaph des Erasmus von Rotterdam im Basler Münster',
    ort: 'Basel',
    bild: 'basel-erasmus/Bild0.jpeg',
    autor: 'Beate Heiniger',
    jahr: '2023',
    markierungen: [[47.55653, 7.59225]],
    kanton: Kantone.BaselStadt,
  },

  '21 "IN SPE ET SILENTIO"': {
    karusselltitel: '"IN SPE ET SILENTIO"',
    verzeichnispfad: 'inspeetsilentio',
    beitragtitel: '"IN SPE ET SILENTIO"',
    ort: 'Trouvaillen',
    bild: 'trouvaille-inspeetsilentio/Bild0.jpeg',
    autor: 'Rudolf Dellsperger',
    jahr: '2023',
    markierungen: [],
    kanton: Kantone.Trouvaillen,
  },

  '20 "Heidelberger" und "Herrliberger" – zwei Titelblätter, zwei Welten': {
    karusselltitel:
      '"Heidelberger" und "Herrliberger" – zwei Titelblätter, zwei Welten',
    verzeichnispfad: 'heidelundherrliberger',
    beitragtitel:
      '"Heidelberger" und "Herrliberger" – zwei Titelblätter, zwei Welten',
    ort: 'Trouvaillen',
    bild: 'trouvaille-heidelundherrliberger/Bild0.jpeg',
    autor: 'Rudolf Dellsperger',
    jahr: '2023',
    markierungen: [],
    kanton: Kantone.Trouvaillen,
  },

  '19 Kirche Kleinhöchstetten und Öki Kehrsatz (BE): «… dass sie alle eins seien»':
    {
      karusselltitel:
        'Kirche Kleinhöchstetten und Öki Kehrsatz (BE): "… dass sie alle eins seien"',
      verzeichnispfad: 'alleeins',
      beitragtitel:
        'Kirche Kleinhöchstetten und Öki Kehrsatz (BE): "… dass sie alle eins seien"',
      ort: 'Trouvaillen',
      bild: 'trouvaille-alleeins/Bild0.jpeg',
      autor: 'Rudolf Dellsperger',
      jahr: '2023 (2008)',
      markierungen: [
        [46.90334, 7.53136],
        [46.91247, 7.47361],
      ],
      kanton: Kantone.Trouvaillen,
    },

  'Einen heiligen Ort schaffen – Zur Bedeutung der Wandmalereien in der Kirche Gsteig im Berner Oberland':
    {
      karusselltitel:
        'Einen heiligen Ort schaffen – Zur Bedeutung der Wandmalereien in der Kirche Gsteig im Berner Oberland',
      verzeichnispfad: 'wandmalereienundheiligkeit',
      beitragtitel:
        'Einen heiligen Ort schaffen – Zur Bedeutung der Wandmalereien in der Kirche Gsteig im Berner Oberland',
      ort: 'Gsteigwiler (BE)',
      bild: 'gsteigwiler-kirche/Bild0.jpeg',
      autor: 'Joana Mayer',
      jahr: '2023',
      markierungen: [[46.665, 7.8725]],
      kanton: Kantone.Bern,
    },

  '18 Zürich, Landesausstellung: Ganz Ohr': {
    karusselltitel: 'Zürich, Landesausstellung: Ganz Ohr',
    verzeichnispfad: 'landizh',
    beitragtitel: 'Zürich, Landesausstellung: Ganz Ohr',
    ort: 'Trouvaillen',
    bild: 'trouvaille-landizh/Bild0.jpeg',
    autor: 'Rudolf Dellsperger',
    jahr: '2022 (2008)',
    markierungen: [[47.3661, 8.5432]],
    kanton: Kantone.Trouvaillen,
  },

  '17 Erlenbach im Simmental (BE): "La cellule d`Erlenbach"': {
    karusselltitel: 'Erlenbach im Simmental (BE): "La cellule d`Erlenbach"',
    verzeichnispfad: 'cellule',
    beitragtitel: 'Erlenbach im Simmental (BE): "La cellule d`Erlenbach"',
    ort: 'Trouvaillen',
    bild: 'trouvaille-cellulederlenbach/Bild0.jpeg',
    autor: 'Rudolf Dellsperger',
    jahr: '2022 (2007)',
    markierungen: [[46.66112, 7.55159]],
    kanton: Kantone.Trouvaillen,
  },

  '16 Bern, Landesausstellung 1914: Gottesfremde': {
    karusselltitel: 'Bern, Landesausstellung 1914: Gottesfremde',
    verzeichnispfad: 'landibern',
    beitragtitel: 'Bern, Landesausstellung 1914: Gottesfremde',
    ort: 'Trouvaillen',
    bild: 'trouvaille-landibern/Bild0.jpeg',
    autor: 'Rudolf Dellsperger',
    jahr: '2022 (2007)',
    markierungen: [[46.9595, 7.4304]],
    kanton: Kantone.Trouvaillen,
  },
  'Im Mutterleib der Erde? Die Quellgrotte der Sainte-Colombe in Undervelier': {
    karusselltitel:
      'Im Mutterleib der Erde? Die Quellgrotte der Sainte-Colombe',
    verzeichnispfad: 'quellgrotte',
    beitragtitel:
      'Im Mutterleib der Erde? Die Quellgrotte der Sainte-Colombe in Undervelier',
    ort: 'Undervelier (JU)',
    bild: 'undervelier-quellgrotte/Bild0.jpeg',
    autor: 'Janina Ammon',
    jahr: '2023',
    markierungen: [[47.30675, 7.21897]],
    kanton: Kantone.Jura,
  },

  '15 Därstetten (BE): "Almosen geben armet nid"': {
    karusselltitel: 'Därstetten (BE): "Almosen geben armet nid"',
    verzeichnispfad: 'daerstetten',
    beitragtitel: 'Därstetten (BE): "Almosen geben armet nid"',
    ort: 'Trouvaillen',
    bild: 'trouvaille-daerstetten/Bild0.jpeg',
    autor: 'Rudolf Dellsperger',
    jahr: '2023 (2007)',
    markierungen: [[46.6559, 7.4969]],
    kanton: Kantone.Trouvaillen,
  },

  '14 Bern West: Vom Zeughaus zum Diakonissenhaus': {
    karusselltitel: 'Bern West: Vom Zeughaus zum Diakonissenhaus',
    verzeichnispfad: 'diakonissenhaus',
    beitragtitel: 'Bern West: Vom Zeughaus zum Diakonissenhaus',
    ort: 'Trouvaillen',
    bild: 'trouvaille-diakonissenhaus/Bild0.jpeg',
    autor: 'Rudolf Dellsperger',
    jahr: '2023 (2007)',
    markierungen: [[46.94959, 7.44305]],
    kanton: Kantone.Trouvaillen,
  },

  '13 Thielle-Wavre (NE): Das alte Haus von Montmirail': {
    karusselltitel: 'Thielle-Wavre (NE): Das alte Haus von Montmirail',
    verzeichnispfad: 'montmirail',
    beitragtitel: 'Thielle-Wavre (NE): Das alte Haus von Montmirail',
    ort: 'Trouvaillen',
    bild: 'trouvaille-montmirail/Bild0.jpeg',
    autor: 'Rudolf Dellsperger',
    jahr: '2023 (2008)',
    markierungen: [[47.01687, 7.02622]],
    kanton: Kantone.Trouvaillen,
  },

  'Trivultus: Dreigesicht Gottes – ein mal eins mal eins gleich eins': {
    karusselltitel:
      'Trivultus: Dreigesicht Gottes – ein mal eins mal eins gleich eins',
    verzeichnispfad: 'trivultus',
    beitragtitel:
      'Trivultus: Dreigesicht Gottes – ein mal eins mal eins gleich eins',
    ort: 'Basel',
    bild: 'basel-trivultus/Bild0.jpeg',
    autor: 'Adriana Basso Schaub',
    jahr: '2023',
    markierungen: [[47.55927, 7.58525]],
    kanton: Kantone.BaselStadt,
  },

  '12 Hindelbank (BE): Es geht nicht alles zugrunde': {
    karusselltitel: 'Hindelbank (BE): Es geht nicht alles zugrunde',
    verzeichnispfad: 'hindelbank',
    beitragtitel: 'Hindelbank (BE): Es geht nicht alles zugrunde',
    ort: 'Trouvaillen',
    bild: 'trouvaille-hindelbank/Bild0.jpeg',
    autor: 'Rudolf Dellsperger',
    jahr: '2022 (2008)',
    markierungen: [[47.04177, 7.54017]],
    kanton: Kantone.Trouvaillen,
  },

  '11 Oberdiessbach (BE): Der Berner Synodus': {
    karusselltitel: 'Oberdiessbach (BE): Der Berner Synodus',
    verzeichnispfad: 'bernersynodus',
    beitragtitel: 'Oberdiessbach (BE): Der Berner Synodus',
    ort: 'Trouvaillen',
    bild: 'trouvaille-oberdiessbach/Bild0.jpeg',
    autor: 'Rudolf Dellsperger',
    jahr: '2022 (2006)',
    markierungen: [[46.84032, 7.61958]],
    kanton: Kantone.Trouvaillen,
  },

  '10 Buchhof (S0): "... damit die christliche Freiheit bleibe"': {
    karusselltitel: 'Buchhof (SO): "... damit die christliche Freiheit bleibe"',
    verzeichnispfad: 'buchhof',
    beitragtitel: 'Buchhof (SO): "... damit die christliche Freiheit bleibe"',
    ort: 'Trouvaillen',
    bild: 'trouvaille-buchhof/Bild0.jpeg',
    autor: 'Rudolf Dellsperger',
    jahr: '2022 (2007)',
    markierungen: [[47.1835, 7.5256]],
    kanton: Kantone.Trouvaillen,
  },

  'St. Clara – Gotteshaus der Katholiken Basels seit 1798': {
    karusselltitel: 'St. Clara – Gotteshaus der Katholiken Basels seit 1798',
    verzeichnispfad: 'clarakirche',
    beitragtitel: 'St. Clara – Gotteshaus der Katholiken Basels seit 1798',
    ort: 'Basel',
    bild: 'basel-clarakirche/Bild0.jpeg',
    autor: 'Patrick Braun',
    jahr: '2022',
    markierungen: [[47.56163, 7.59416]],
    kanton: Kantone.BaselStadt,
  },

  '9 Bern, Heiliggeistkirche: Für Burger und Strafgefangene': {
    karusselltitel: 'Bern, Heiliggeistkirche: Für Burger und Strafgefangene',
    verzeichnispfad: 'burgerundstrafgefangene',
    beitragtitel: 'Bern, Heiliggeistkirche: Für Burger und Strafgefangene',
    ort: 'Trouvaillen',
    bild: 'trouvaille-burgerundstrafgefangene/Bild0.jpeg',
    autor: 'Rudolf Dellsperger',
    jahr: '2022 (2007)',
    markierungen: [[46.948, 7.44073]],
    kanton: Kantone.Trouvaillen,
  },

  '8 Bätterkinden (BE): Das "Oeil-de-boeuf"-Fenster': {
    karusselltitel: 'Bätterkinden (BE): Das "Oeil-de-boeuf"-Fenster',
    verzeichnispfad: 'oeildeboeuf',
    beitragtitel: 'Bätterkinden (BE): Das "Oeil-de-boeuf"-Fenster',
    ort: 'Trouvaillen',
    bild: 'trouvaille-oeildeboeuf/Bild0.jpeg',
    autor: 'Rudolf Dellsperger',
    jahr: '2022 (2007)',
    markierungen: [[47.12895, 7.54056]],
    kanton: Kantone.Trouvaillen,
  },

  '7 Bern, Kirche und Staat - ein Balanceakt': {
    karusselltitel: 'Bern, Kirche und Staat - ein Balanceakt',
    verzeichnispfad: 'kircheundstaat',
    beitragtitel: 'Bern, Kirche und Staat - ein Balanceakt',
    ort: 'Trouvaillen',
    bild: 'trouvaille-kircheundstaat/Bild0.jpeg',
    autor: 'Rudolf Dellsperger',
    jahr: '2022 (2007)',
    markierungen: [
      [46.9487, 7.45235],
      [46.94724, 7.45153],
    ],
    kanton: Kantone.Trouvaillen,
  },

  'Sankt Martin und der Räbeliechtliumzug in Oberrohrdorf': {
    karusselltitel: 'Sankt Martin und der Räbeliechtliumzug in Oberrohrdorf',
    verzeichnispfad: 'raebeliechtli',
    beitragtitel: 'Sankt Martin und der Räbeliechtliumzug in Oberrohrdorf',
    ort: 'Oberrohrdorf (AG)',
    bild: 'oberrohrdorf-martinundraebeliechtli/Bild0.jpeg',
    autor: 'Tabea Stauffer',
    jahr: '2022',
    markierungen: [[47.41906, 8.31497]],
    kanton: Kantone.Aargau,
  },

  '6 Bern, Matte: Ländtetor': {
    karusselltitel: 'Bern, Matte: Ländtetor',
    verzeichnispfad: 'mattelaendtetor',
    beitragtitel: 'Bern, Matte: Ländtetor',
    ort: 'Trouvaillen',
    bild: 'trouvaille-mattelaendtetor/Bild1.jpeg',
    autor: 'Rudolf Dellsperger',
    jahr: '2022 (2006)',
    markierungen: [[46.94897, 7.45807]],
    kanton: Kantone.Trouvaillen,
  },

  '5 Kirche Einigen (BE): "Unser täglich Brot ..."': {
    karusselltitel: 'Kirche Einigen (BE): "Unser täglich Brot ..."',
    verzeichnispfad: 'unsertaeglichbrot',
    beitragtitel: 'Kirche Einigen (BE): "Unser täglich Brot ..."',
    ort: 'Trouvaillen',
    bild: 'trouvaille-unsertaeglichbrot/Bild0.jpeg',
    autor: 'Rudolf Dellsperger',
    jahr: '2022 (2006)',
    markierungen: [[46.70941, 7.64619]],
    kanton: Kantone.Trouvaillen,
  },

  '4 Hausspruch Herrengasse 13': {
    karusselltitel: 'Bern, Herrengasse 13: Hausspruch',
    verzeichnispfad: 'herrengasse13',
    beitragtitel: 'Bern, Herrengasse 13: Hausspruch',
    ort: 'Trouvaillen',
    bild: 'trouvaille-herrengasse13/Bild0.jpeg',
    autor: 'Rudolf Dellsperger',
    jahr: '2022 (2006)',
    markierungen: [[46.947, 7.44992]],
    kanton: Kantone.Trouvaillen,
  },

  'Église Saint-Jean-Baptiste': {
    karusselltitel: 'Église Saint-Jean-Baptiste',
    verzeichnispfad: 'Saint-Jean-Baptiste',
    beitragtitel: 'Prädikat: «Mérite un détour»',
    ort: 'Gland (VD)',
    bild: 'gland-saint-jean-baptiste/Bild1.jpeg',
    autor: 'David Zimmer',
    jahr: '2022',
    markierungen: [[46.42244, 6.26538]],
    kanton: Kantone.Waadt,
  },

  'Basel Galluspforte': {
    karusselltitel: 'Die Galluspforte am Basler Münster',
    verzeichnispfad: 'Die Galluspforte am Basler Münster',
    beitragtitel: 'Die Galluspforte am Basler Münster',
    ort: 'Basel',
    bild: 'basel-galluspforte/Bild0.jpeg',
    autor: 'Silvan Beer',
    jahr: '2022',
    markierungen: [[47.55662, 7.5923]],
    kanton: Kantone.BaselStadt,
  },

  '3 "unserer frauen bruderschaft"': {
    karusselltitel: 'Berner Münster: "unserer frauen bruderschaft"',
    verzeichnispfad: 'unsererfrauenbruderschaft',
    beitragtitel: 'Berner Münster: "unserer frauen bruderschaft"',
    ort: 'Trouvaillen',
    bild: 'trouvaille-unsererfrauenbruderschaft/Bild0.jpeg',
    autor: 'Rudolf Dellsperger',
    jahr: '2022 (2006)',
    markierungen: [[46.9473, 7.45186]],
    kanton: Kantone.Trouvaillen,
  },

  '2 Beatus lacht': {
    karusselltitel: 'Dreifaltigkeitkirche Bern / Kirche Einigen: Beatus lacht',
    verzeichnispfad: 'beatuslacht',
    beitragtitel: 'Dreifaltigkeitkirche Bern / Kirche Einigen: Beatus lacht',
    ort: 'Trouvaillen',
    bild: 'trouvaille-beatuslacht/Bild0.jpeg',
    autor: 'Rudolf Dellsperger',
    jahr: '2022 (2008)',
    markierungen: [
      [46.94512, 7.43932],
      [46.70941, 7.64619],
    ],
    kanton: Kantone.Trouvaillen,
  },

  '1 Christus und die Kirche': {
    karusselltitel: 'Münchenwiler (BE): Christus und die Kirche',
    verzeichnispfad: 'muenchenwilerchristusundkirche',
    beitragtitel: 'Münchenwiler (BE): Christus und die Kirche',
    ort: 'Trouvaillen',
    bild: 'trouvaille-muenchenwiler-christus-kirche/Bild0.jpeg',
    autor: 'Rudolf Dellsperger',
    jahr: '2022 (2007)',
    markierungen: [[46.9122, 7.127]],
    kanton: Kantone.Trouvaillen,
  },

  'St. Mangen - Die älteste Kirche der Stadt St. Gallen': {
    karusselltitel: 'St. Mangen - Die älteste Kirche der Stadt St. Gallen',
    verzeichnispfad: 'St. Mangen - Die älteste Kirche der Stadt St. Gallen',
    beitragtitel: 'St. Mangen - Die älteste Kirche der Stadt St. Gallen',
    ort: 'St. Gallen',
    bild: 'st-mangen-wiborada/Bild1.jpeg',
    autor: 'Ann-Katrin Gässlein',
    jahr: '2022',
    markierungen: [[47.42775, 9.37616]],
    kanton: Kantone.SanktGallen,
  },

  'Wallfahrtskirche Mariä Himmelfahrt': {
    karusselltitel: 'Wallfahrtskirche Mariä Himmelfahrt',
    verzeichnispfad: 'Wallfahrtskirche Mariä Himmelfahrt',
    beitragtitel: 'Wallfahrtskirche Mariä Himmelfahrt in Oberdorf',
    ort: 'Oberdorf (SO)',
    bild: 'oberdorf-wallfahrtskirche/Bild1.jpg',
    autor: 'Peter Widmer',
    jahr: '2022',
    markierungen: [[47.2293, 7.503]],
    kanton: Kantone.Solothurn,
  },

  'Das Amphitheater Vindonissa': {
    karusselltitel: 'Das Amphitheater Vindonissa',
    verzeichnispfad: 'Das Amphitheater Vindonissa',
    beitragtitel: 'Vom Kultort zur Kulturstätte: Das Amphitheater Vindonissa',
    ort: 'Windisch (AG)',
    bild: 'windisch-das-amphitheater-vindonissa/bild1.jpg',
    autor: 'Tabea Stauffer',
    jahr: '2022',
    markierungen: [[47.47628, 8.21373]],
    kanton: Kantone.Aargau,
  },
  'Totentanz Basel': {
    karusselltitel: 'Totentanz',
    verzeichnispfad: 'Totentanz',
    beitragtitel: 'Vom tanzenden Tod ...',
    ort: 'Basel',
    bild: 'basel-totentanz/bild1.jpeg',
    autor: 'Michael Bangert',
    jahr: '2022',
    markierungen: [[47.56201, 7.58523]],
    kanton: Kantone.BaselStadt,
  },

  'Tempelland der Schweizer Bahai-Gemeinde': {
    karusselltitel: 'Tempelland der Schweizer Bahai-Gemeinde',
    verzeichnispfad: 'Tempelland der Schweizer Bahai-Gemeinde',
    beitragtitel: 'Haus der Andacht mit Blick auf die Berge',
    ort: 'Kirchenthurnen (BE)',
    bild: 'kirchenthurnen-bahai/bild1.jpg',
    autor: 'Ruth Merz',
    jahr: '2022',
    markierungen: [[46.8219, 7.5007]],
    kanton: Kantone.Bern,
  },

  'Kunstprojekt Cantus firmus': {
    karusselltitel: 'Kunstprojekt Cantus firmus',
    verzeichnispfad: 'Kunstprojekt Cantus firmus',
    beitragtitel:
      'Cantus firmus - Kommunikation zwischen Mikrokosmos und Makrokosmos',
    ort: 'Solothurn',
    bild: 'solothurn-cantus-firmus/bild5.jpeg',
    autor: 'Adriana Basso Schaub',
    jahr: '2022',
    markierungen: [[47.209, 7.53763]],
    kanton: Kantone.Solothurn,
  },
  'Die Soeurs grises von Solothurn': {
    karusselltitel: 'Die Sœurs grises von Solothurn',
    verzeichnispfad: 'Die Soeurs grises von Solothurn',
    beitragtitel:
      'Krankenpflege in der frühen Neuzeit - Die Sœurs grises von Solothurn',
    ort: 'Solothurn',
    bild: 'solothurn-soeurs-grises/bild2.jpeg',
    autor: 'Ulrike Münger',
    jahr: '2022',
    markierungen: [[47.20506, 7.53587]],
    kanton: Kantone.Solothurn,
  },

  'Poschiavo Friedhof Hildesheimers Grab': {
    karusselltitel: 'Friedhof Hildesheimers Grab',
    verzeichnispfad: 'Friedhof Hildesheimers Grab',
    beitragtitel: 'Auf den Spuren der Steinchen auf den Grabsteinen',
    ort: 'Poschiavo (GR)',
    bild: 'poschiavo-friedhof-hildesheimers-grab/bild4.jpeg',
    autor: 'Valérie Rhein',
    jahr: '2022',
    markierungen: [[46.32675, 10.0591]],
    kanton: Kantone.Graubünden,
  },
  'Kleinhöchstetten evangelisch-reformierte Kirche': {
    karusselltitel: 'Die evangelisch-reformierte Kirche',
    verzeichnispfad: 'Die evangelisch-reformierte Kirche',
    beitragtitel:
      'Ältester erhaltener frühromanischer Sakralbau im Bernbiet und Ausgangspunkt der Berner Reformation ',
    ort: 'Kleinhöchstetten (BE)',
    bild: 'kleinhoechstetten-kirche/bild0.jpeg',
    autor: 'Miriam Löhr',
    jahr: '2022',
    markierungen: [[46.90329, 7.53132]],
    kanton: Kantone.Bern,
  },
  'Rüegsau Reformierte Kirche': {
    karusselltitel: 'Reformierte Kirche',
    verzeichnispfad: 'Reformierte Kirche',
    beitragtitel: 'Reformierte Kirche Rüegsau',
    ort: 'Rüegsau (BE)',
    bild: 'rueegsau-kirche/bild1.jpg',
    autor: 'Rolf Weibel',
    jahr: '2021',
    markierungen: [[47.02472, 7.67451]],
    kanton: Kantone.Bern,
  },
  'Visp St. Martinskirche': {
    karusselltitel: 'St. Martinskirche Visp',
    verzeichnispfad: 'St. Martinskirche Visp',
    beitragtitel: 'Die St. Martinskirche Visp',
    ort: 'Visp (VS)',
    bild: 'visp-martinskirche/bild1.jpeg',
    autor: 'Damian Pfammatter',
    jahr: '2021',
    markierungen: [[46.28911, 7.88096]],
    kanton: Kantone.Wallis,
  },
  'Erlenbach Sankt Michaelskirche': {
    karusselltitel: 'Sankt Michaelskirche',
    verzeichnispfad: 'Sankt Michaelskirche',
    beitragtitel: 'Die Sankt Michaelskirche von Erlenbach im Simmental',
    ort: 'Erlenbach (BE)',
    bild: 'erlenbach-sankt-michaelskirche/bild2.jpeg',
    autor: 'Hans Hofer',
    jahr: '2021',
    markierungen: [[46.66085, 7.5519]],
    kanton: Kantone.Bern,
  },
  'Aletschgletscher Arme Seelen': {
    karusselltitel: 'Gletschersage',
    verzeichnispfad: 'Gletschersage',
    beitragtitel: 'Von den Armen Seelen im Gletscher',
    ort: 'Aletschgletscher (VS)',
    bild: 'aletschgletscher-arme-seelen/bild1.JPG',
    autor: 'Andreas Weissen',
    jahr: '2021',
    markierungen: [[46.39207, 8.0023]],
    kanton: Kantone.Wallis,
  },
  'Solothurn Spitalkirche': {
    karusselltitel: 'Spitalkirche',
    verzeichnispfad: 'Spitalkirche',
    beitragtitel: 'Spitalkirche zum Heiligen Geist in Solothurn',
    ort: 'Solothurn',
    bild: 'solothurn-spitalkirche/bild1.jpg',
    autor: 'Deborah Finger-Oppliger',
    jahr: '2021',
    markierungen: [[47.20506, 7.53587]],
    kanton: Kantone.Solothurn,
  },
  'Solothurn zwei Heilige': {
    karusselltitel: 'Solothurn Zwei Heilige',
    verzeichnispfad: 'Solothurn Zwei Heilige',
    beitragtitel: 'Zwei Heilige überblicken Solothurn',
    ort: 'Solothurn',
    bild: 'solothurn-zwei-heilige/bild1.jpg',
    autor: 'Joël Meier',
    jahr: '2021',
    markierungen: [[47.2083, 7.53934]],
    kanton: Kantone.Solothurn,
  },
  Filmpodium: {
    karusselltitel: 'Filmpodium',
    verzeichnispfad: 'Filmpodium',
    beitragtitel: 'C’est où, le Filmpodium?',
    bild: 'biel-filmpodium/bild1.jpg',
    ort: 'Biel (BE)',
    autor: 'Sina von Aesch',
    jahr: '2021',
    markierungen: [[47.1389, 7.2397]],
    kanton: Kantone.Bern,
  },
  'Weitblick und Enge': {
    karusselltitel: 'Weitblick und Enge',
    verzeichnispfad: 'Weitblick und Enge',
    beitragtitel: 'Weitblick und Enge im Luzerner Hinterland',
    ort: 'Sulzig/Werthenstein (LU)',
    bild: 'sulzig-weitblick/bild1.jpg',
    autor: 'Gregor Emmenegger, David Neuhold, Anton Schwingruber',
    jahr: '2021',
    markierungen: [[47.0445, 8.08993]],
    kanton: Kantone.Luzern,
  },
  'Basel Jüdisches Museum': {
    karusselltitel: 'Jüdisches Museum',
    verzeichnispfad: 'Jüdisches Museum',
    beitragtitel: 'Kulturhistorisches Schaufenster der jüdischen Schweiz',
    ort: 'Basel',
    bild: 'basel-juedisches-museum/bild3.jpg',
    autor: 'David Zimmer',
    jahr: '2021',
    markierungen: [
      [47.55652, 7.58335],
      [47.5576245, 7.5830794],
    ],
    kanton: Kantone.BaselStadt,
  },
  Klosterort: {
    karusselltitel: 'Klosterort',
    verzeichnispfad: 'Klosterort',
    beitragtitel: 'Mariastein, ein Wallfahrts- und Klosterort',
    bild: 'mariastein-klosterort/bild1.jpg',
    ort: 'Mariastein (SO)',
    autor: 'Pater Lukas Schenker',
    jahr: '2021',
    markierungen: [[47.47603, 7.49302]],
    kanton: Kantone.Solothurn,
  },
  Spreuerbrücke: {
    karusselltitel: 'Spreuerbrücke',
    verzeichnispfad: 'Spreuerbrücke',
    beitragtitel: 'Die Spreuerbrücke in Luzern',
    bild: 'luzern-spreuerbruecke/bild1.jpg',
    ort: 'Luzern',
    autor: 'Sina von Aesch',
    jahr: '2021',
    markierungen: [[47.05183, 8.30165]],
    kanton: Kantone.Luzern,
  },
  Benediktinerkloster: {
    karusselltitel: 'Benediktinerkloster',
    verzeichnispfad: 'Benediktinerkloster',
    beitragtitel: 'Benediktinerkloster Disentis',
    bild: 'disentis-benediktinerkloster/bild2.jpeg',
    ort: 'Disentis (GR)',
    autor: 'Jan Peter Lang',
    jahr: '2021',
    markierungen: [[46.7071, 8.8563]],
    kanton: Kantone.Graubünden,
  },

  'Simplon Hospiz': {
    karusselltitel: 'Simplon Hospiz',
    verzeichnispfad: 'Simplon Hospiz',
    beitragtitel: 'Simplon Hospiz',
    ort: 'Simplon Pass (VS)',
    bild: 'simplon-pass-hospiz/bild1.jpg',
    autor: 'Daniel Salzgeber',
    jahr: '2021',
    markierungen: [[46.2467, 8.0293]],
    kanton: Kantone.Wallis,
  },
  'Bern Ökumenische Kirche im Haus der Religionen': {
    karusselltitel: 'Ökumenische Kirche im Haus der Religionen',
    verzeichnispfad: 'Ökumenische Kirche im Haus der Religionen',
    beitragtitel: 'Ökumenische Kirche im Haus der Religionen',
    bild: 'bern-oekumenische-kirche-hdr/bild0.jpeg',
    ort: 'Bern',
    autor: 'Angela Büchel Sladkovic, Frieder Vollprecht, Christian Walti ',
    jahr: '2021',
    markierungen: [[46.94362, 7.40597]],
    kanton: Kantone.Bern,
  },
  'Berner Totentanz': {
    karusselltitel: 'Berner Totentanz',
    verzeichnispfad: 'Berner Totentanz',
    beitragtitel: 'Berner Totentanz',
    bild: 'bern-totentanz/bild1.jpg',
    ort: 'Bern',
    autor: 'Matthias D. Berger',
    jahr: '2021',
    markierungen: [[46.94895, 7.44642]],
    kanton: Kantone.Bern,
  },
  Verenaschlucht: {
    karusselltitel: 'Verenaschlucht',
    verzeichnispfad: 'Verenaschlucht',
    beitragtitel: 'Die Heilige Verena bei Solothurn',
    bild: 'ruettenen-verenaschlucht/bild1.jpg',
    ort: 'Rüttenen (SO)',
    autor: 'Raphael Hadorn',
    jahr: '2021',
    markierungen: [[47.2246, 7.534]],
    kanton: Kantone.Solothurn,
  },
  'Begegnungen in Bethlehem': {
    karusselltitel: 'Begegnungen in Bethlehem',
    verzeichnispfad: 'Begegnungen in Bethlehem',
    beitragtitel: 'Begegnungen in Bethlehem',
    bild: 'bethlehem-kirche/bernbetlehem.jpg',
    ort: 'Bethlehem (BE)',
    autor: 'Andreas Köhler-Andereggen',
    jahr: '2020',
    markierungen: [[46.9495, 7.3927]],
    kanton: Kantone.Bern,
  },
  Kapelle: {
    karusselltitel: 'Kapelle',
    verzeichnispfad: 'Kapelle',
    beitragtitel: 'Die Kapelle auf der Belalp/Lüsga',
    bild: 'belalp-kapelle/belalpKapelle.jpg',
    ort: 'Belalp (VS)',
    autor: 'Gerd Dönni',
    jahr: '2020',
    markierungen: [[46.3813, 7.99124]],
    kanton: Kantone.Wallis,
  },
  Kollegiumskirche: {
    karusselltitel: 'Kollegiumskirche',
    verzeichnispfad: 'Kollegiumskirche',
    beitragtitel: 'Die Kollegiumskirche zum Heiligen Geist in Brig',
    bild: 'brig-kollegiumskirche/bild2.jpg',
    ort: 'Brig (VS)',
    autor: 'Gerd Dönni',
    jahr: '2020',
    markierungen: [[46.3153, 7.99214]],
    kanton: Kantone.Wallis,
  },
  Kindlifresserbrunnen: {
    karusselltitel: 'Kindlifresserbrunnen',
    verzeichnispfad: 'Kindlifresserbrunnen',
    beitragtitel:
      'Von Kinderfressern und der Relevanz der Juden für die Christen',
    bild: 'bern-kindlifresser/bild1.jpg',
    ort: 'Bern',
    autor: 'René Bloch',
    jahr: '2020',
    markierungen: [[46.94849, 7.4475]],
    kanton: Kantone.Bern,
  },
  'Swiss Church in London': {
    karusselltitel: 'Swiss Church in London',
    verzeichnispfad: 'Swiss Church in London',
    beitragtitel: 'The Swiss Church in London',
    ort: 'London',
    bild: 'london-church/bild1.jpg',
    autor: 'Carla Maurer',
    jahr: '2020',
    markierungen: [[51.5154, -0.1262]],
    kanton: Kantone.London,
  },
  'Ehemaliges Burgerspital': {
    karusselltitel: 'Ehemaliges Burgerspital',
    verzeichnispfad: 'Ehemaliges Burgerspital',
    beitragtitel: 'Von goldenen Lettern und der Fremdheit ihrer Hoffnung',
    bild: 'bern-burgerspital/burgerspital2.jpeg',
    ort: 'Bern',
    autor: 'Matthias Käser',
    jahr: '2020',
    markierungen: [[46.94774, 7.4393]],
    kanton: Kantone.Bern,
  },
  'Amsoldingen Kirche': {
    karusselltitel: 'Amsoldingen Kirche',
    verzeichnispfad: 'Amsoldingen Kirche',
    beitragtitel: 'Die Kirche Amsoldingen – ein Juwel im Berner Oberland',
    bild: 'amsoldingen-kirche/amsoldingen.jpg',
    ort: 'Amsoldingen (BE)',
    autor: 'Nicole Hublard',
    jahr: '2020',
    markierungen: [[46.7272, 7.57891]],
    kanton: Kantone.Bern,
  },
  'Studium der Ostkirchen': {
    karusselltitel: 'Studium der Ostkirchen',
    verzeichnispfad: 'Studium der Ostkirchen',
    beitragtitel:
      'Zentrum für das Studium der Ostkirchen an der Universität Freiburg: Orthodoxe Spiritualität in einer Universität katholischer Prägung',
    bild: 'freiburg-zentrum/bild3.jpg',
    ort: 'Freiburg',
    autor: 'Stefan Constantinescu',
    jahr: '2020',
    markierungen: [[46.80643, 7.15137]],
    kanton: Kantone.Fribourg,
  },
  'Études des Églises d’Orient': {
    karusselltitel: 'Centre d’études des Églises d’Orient',
    verzeichnispfad: 'Etudes des Eglises dOrient',
    beitragtitel:
      'Centre d’études des Églises d’Orient à l’Université de Fribourg: La spiritualité orthodoxe dans une université à caractère catholique',
    bild: 'freiburg-centre-dorient/bild3.jpg',
    ort: 'Freiburg',
    autor: 'Stefan Constantinescu',
    jahr: '2020',
    markierungen: [[46.80643, 7.15137]],
    kanton: Kantone.Fribourg,
  },
  'Antoniterkirche Antonius-Fresken': {
    karusselltitel: 'Antoniterkirche Antonius-Fresken',
    verzeichnispfad: 'Antoniterkirche Antonius-Fresken',
    beitragtitel:
      'Die Antonius-Fresken von Fritz Pauli – ein reformiertes Bildprogramm',
    bild: 'bern-antoniterkirche-antonius-fresken/antonbild3.jpg',
    ort: 'Bern',
    autor: 'Katharina Heyden',
    jahr: '2020',
    markierungen: [[46.94895, 7.45359]],
    kanton: Kantone.Bern,
  },
  'Kraftwerk Birsfelden': {
    karusselltitel: 'Kraftwerk Birsfelden',
    verzeichnispfad: 'Kraftwerk Birsfelden',
    beitragtitel:
      'Das Kraftwerk Birsfelden – ein theologischer Erinnerungsort?',
    bild: 'birsfelden-kraftwerk/bild1.jpg',
    ort: 'Birsfelden (BL)',
    autor: 'Georg Kreis',
    jahr: '2020',
    markierungen: [[47.5605, 7.6259]],
    kanton: Kantone.BaselLand,
  },
  'Stationenweg zur Täufergeschichte': {
    karusselltitel: 'Stationenweg zur Täufergeschichte',
    verzeichnispfad: 'Stationenweg zur Täufergeschichte',
    beitragtitel: 'Stationenweg zur Täufergeschichte',
    bild: 'bern-taeufergeschichte/bild2.jpg',
    ort: 'Bern',
    autor: 'Dorothea Loosli-Amstutz',
    jahr: '2020',
    markierungen: [[46.94742, 7.45157]],
    kanton: Kantone.Bern,
  },
  'Dürrenmatts Mansarde': {
    karusselltitel: 'Dürrenmatts Mansarde',
    verzeichnispfad: 'Dürrenmatts Mansarde',
    beitragtitel: 'Dürrenmatts Mansarde',
    bild: 'bern-duerrenmatt-mansarde/bild2.jpg',
    ort: 'Bern',
    autor: 'Christoph Morgenthaler',
    jahr: '2020',
    markierungen: [[46.94872, 7.46459]],
    kanton: Kantone.Bern,
  },
  'Münster Portal': {
    karusselltitel: 'Münster Portal',
    verzeichnispfad: 'Münster Portal',
    beitragtitel:
      'Vom Wiegen des Herzens und Feuerseen – Altägyptische Unterweltsvorstellungen am Portal des Berner Münsters?',
    bild: 'bern-muenster-portal/bild1.jpg',
    ort: 'Bern',
    autor: 'Ulrike Münger',
    jahr: '2019',
    markierungen: [[46.94723, 7.45134]],
    kanton: Kantone.Bern,
  },
  'Hebammenpforte des Berner Münsters': {
    karusselltitel: 'Hebammenpforte des Berner Münsters',
    verzeichnispfad: 'Hebammenpforte des Berner Münsters',
    beitragtitel: 'Hebammenpforte des Berner Münsters',
    bild: 'bern-hebammenpforte/bild1.jpg',
    ort: 'Bern',
    autor: 'Adrienne Shannon Grossenbacher',
    jahr: '2019',
    markierungen: [[46.94741, 7.45157]],
    kanton: Kantone.Bern,
  },
  'Martinskirche Rüeggisberg': {
    karusselltitel: 'Martinskirche Rüeggisberg',
    verzeichnispfad: 'Martinskirche Rüeggisberg',
    beitragtitel: 'Martinskirche Rüeggisberg',
    bild: 'rueggisberg-martinskirche/bild3.jpg',
    ort: 'Rüeggisberg (BE)',
    autor: 'Elisabeth Willen-Lanzrein',
    jahr: '2019',
    markierungen: [[46.8215, 7.4387]],
    kanton: Kantone.Bern,
  },
  'Ökumenisches Institut': {
    karusselltitel: 'Ökumenisches Institut',
    verzeichnispfad: 'Ökumenisches Institut',
    beitragtitel:
      'Ökumenisches Institut Bossey – einzigartiges Laboratorium der ökumenischen Bewegung',
    bild: 'bossey-institut/bild1.jpg',
    ort: 'Bogis-Bossey (VD)',
    autor: 'David Zimmer',
    jahr: '2019',
    markierungen: [[46.34756, 6.18565]],
    kanton: Kantone.Waadt,
  },
  'Der Heilige Vinzenz als Kirchenpatron des Berner Münsters': {
    karusselltitel: 'Münster St. Vinzenz',
    verzeichnispfad: 'Münster St. Vinzenz',
    beitragtitel: 'Der Heilige Vinzenz als Kirchenpatron des Berner Münsters',
    bild: 'bern-muenster-vinzenz/bild1.jpg',
    ort: 'Bern',
    autor: 'Alexandra Kreyden',
    jahr: '2019',
    markierungen: [[46.94743, 7.45157]],
    kanton: Kantone.Bern,
  },
  Gnadenbrunnen: {
    karusselltitel: 'Gnadenbrunnen',
    verzeichnispfad: 'Gnadenbrunnen',
    beitragtitel: 'Das Wunderwasser der Luzerner Bauern',
    bild: 'luthernbad-gnadenbrunnen/bild1.jpg',
    ort: 'Luthernbad (LU)',
    autor: 'Hans Herrmann',
    jahr: '2019',
    markierungen: [[47.02541, 7.92512]],
    kanton: Kantone.Luzern,
  },
  'Scherzligen Kirche': {
    karusselltitel: 'Scherzligen Kirche',
    verzeichnispfad: 'Scherzligen Kirche',
    beitragtitel: '«Early Adopter» am Ausfluss des Thunersees',
    bild: 'scherzligen-kirche/bild1.jpg',
    ort: 'Thun (BE)',
    autor: 'Markus Nägeli',
    jahr: '2019',
    markierungen: [[46.74735, 7.63631]],
    kanton: Kantone.Bern,
  },
  'Hindelbank Kirche': {
    karusselltitel: 'Hindelbank Kirche',
    verzeichnispfad: 'Hindelbank Kirche',
    beitragtitel: 'Die Kraft der Auferstehung in Stein gemeisselt',
    bild: 'hindelbank-kirche/bild1.jpg',
    ort: 'Hindelbank (BE)',
    autor: 'Hans Herrmann',
    jahr: '2019',
    markierungen: [[47.04184, 7.54023]],
    kanton: Kantone.Bern,
  },
  Vincentiustafel: {
    karusselltitel: 'Vincentiustafel',
    verzeichnispfad: 'Vincentiustafel',
    beitragtitel:
      'Von Engeln getragen. Der Märtyrer Vincentius von Saragossa im Basler Münster',
    bild: 'basel-vincentiustafel/vincentiustafel.jpg',
    ort: 'Basel',
    autor: 'Maria Lissek',
    jahr: '2018',
    markierungen: [[47.5565, 7.5925]],
    kanton: Kantone.BaselStadt,
  },
  'Cigognier-Heiligtum': {
    karusselltitel: 'Cigognier-Heiligtum',
    verzeichnispfad: 'Cigognier-Heiligtum',
    beitragtitel: 'Das Cigognier-Heiligtum und der Kaiserkult',
    bild: 'avenches-cigognier-heiligtum/avenches.jpg',
    ort: 'Avenches (VD)',
    autor: 'Sara Egger',
    jahr: '2018',
    markierungen: [[46.881, 7.04265]],
    kanton: Kantone.Waadt,
  },
  'Riva San Vitale Baptisterium': {
    karusselltitel: 'San Vitale Baptisterium',
    verzeichnispfad: 'San Vitale Baptisterium',
    beitragtitel:
      'Baptisterien aus dem 5. und 6. Jahrhundert in der heutigen Schweiz',
    ort: 'Riva San Vitale (TI)',
    bild: 'riva-san-vitale-baptisterium/bild0.jpeg',
    autor: 'Maria Lissek',
    jahr: '2016',
    markierungen: [
      [47.58543, 8.30062],
      [45.90469, 8.97095],
      [46.2197, 7.00367],
    ],
    kanton: Kantone.Tessin,
  },
  Feder: {
    karusselltitel: 'Feder',
    verzeichnispfad: 'Feder',
    beitragtitel: 'Eine bewegende Feder als Wallfahrtsziel?',
    bild: 'bueren-feder/bild1.jpg',
    ort: 'Büren an der Aare (BE)',
    autor: 'Dominik von Allmen',
    jahr: '2016',
    markierungen: [[47.13749, 7.38003]],
    kanton: Kantone.Bern,
  },
  'Synagogen und Friedhof': {
    karusselltitel: 'Synagogen und Friedhof',
    verzeichnispfad: 'Synagogen und Friedhof',
    beitragtitel: 'Der «gute Ort», ein Haus für die Ewigkeit',
    bild: 'endingen-friedhof/bild2.jpg',
    ort: 'Endingen (AG)',
    autor: 'René Bloch',
    jahr: '2016',
    markierungen: [[47.5332, 8.3089]],
    kanton: Kantone.Aargau,
  },
  'Saint Maurice Baptisterium': {
    karusselltitel: 'Saint Maurice Baptisterium',
    verzeichnispfad: 'Saint Maurice Baptisterium',
    beitragtitel:
      'Baptisterien aus dem 5. und 6. Jahrhundert in der heutigen Schweiz',
    ort: 'Saint Maurice (VS)',
    bild: 'saint-maurice-baptisterium/bild0.jpeg',
    autor: 'Maria Lissek',
    jahr: '2016',
    markierungen: [
      [47.58543, 8.30062],
      [45.90469, 8.97095],
      [46.2197, 7.00367],
    ],
    kanton: Kantone.Tessin,
  },
  Abbatiale: {
    karusselltitel: 'L’abbatiale de Bellelay',
    verzeichnispfad: 'Abbatiale',
    beitragtitel:
      'L’abbatiale de Bellelay – échos du passé et musique d’avenir',
    bild: 'bellelay-abbatiale/abbatiale.jpg',
    ort: 'Bellelay (BE)',
    autor: 'Lara A. Kneubühler',
    jahr: '2016',
    markierungen: [[47.26409, 7.16869]],
    kanton: Kantone.Bern,
  },
  'Zentrum Paul Klee': {
    karusselltitel: 'Zentrum Paul Klee',
    verzeichnispfad: 'Zentrum Paul Klee',
    beitragtitel: 'Ein Ort für Transzendenzerfahrungen?',
    bild: 'bern-paul-klee/bild1.jpg',
    ort: 'Bern',
    autor: 'Magdalene L. Frettlöh',
    jahr: '2016',
    markierungen: [[46.94907, 7.47429]],
    kanton: Kantone.Bern,
  },
  Baptisterium: {
    karusselltitel: 'Baptisterium',
    verzeichnispfad: 'Baptisterium',
    beitragtitel:
      'Baptisterien aus dem 5. und 6. Jahrhundert in der heutigen Schweiz',
    bild: 'badzurzach-baptisterium/bad_zurzach_baptisterium.jpg',
    ort: 'Bad Zurzach (AG)',
    autor: 'Maria Lissek',
    jahr: '2016',
    markierungen: [
      [47.58543, 8.30062],
      [45.90469, 8.97095],
      [46.2197, 7.00367],
    ],
    kanton: Kantone.Aargau,
  },
  'Kirche St.Martin': {
    karusselltitel: 'Kirche St.Martin',
    verzeichnispfad: 'Kirche St.Martin',
    beitragtitel:
      'Spuren eines vielfachen Erinnerungsträgers – Martin von Tours und seine Kultorte',
    bild: 'basel-martinskirche/bild1.jpg',
    ort: 'Basel',
    autor: 'Angela Berlis',
    jahr: '2016',
    markierungen: [
      [47.55907, 7.58861],
      [47.53123, 7.8109],
      [46.63449, 9.44162],
    ],
    kanton: Kantone.BaselStadt,
  },
  Antoniterkirche: {
    karusselltitel: 'Antoniterkirche',
    verzeichnispfad: 'Antoniterkirche',
    beitragtitel:
      'Himmel, Erde, West und Ost – Die Antoniterkirche in der Berner Altstadt',
    bild: 'bern-antoniterkirche/antoniterkirche_heimlich.jpg',
    ort: 'Bern',
    autor: 'Nadja Heimlicher',
    jahr: '2016',
    markierungen: [[46.94895, 7.45359]],
    kanton: Kantone.Bern,
  },
  'Haus der Religionen': {
    karusselltitel: 'Haus der Religionen',
    verzeichnispfad: 'Haus der Religionen',
    beitragtitel: 'Haus der Religionen: Das Mit- und Nebeneinander gestalten',
    bild: 'bern-haus-der-religionen/bild1.jpg',
    ort: 'Bern',
    autor: 'Anna-Konstanze Schröder',
    jahr: '2016',
    markierungen: [[46.94362, 7.40597]],
    kanton: Kantone.Bern,
  },
  'Schloss Gottlieben': {
    karusselltitel: 'Schloss Gottlieben',
    verzeichnispfad: 'Schloss Gottlieben',
    beitragtitel: 'Gefängnis des Reformators Jan Hus',
    bild: 'gottlieben-schloss/bild1.jpg',
    ort: 'Gottlieben (TG)',
    autor: 'Zbynek Kindschi Garsky',
    jahr: '2016',
    markierungen: [[47.66405, 9.13602]],
    kanton: Kantone.Thurgau,
  },
  'Maennedorf Zentrum der Heiligungsbewegung': {
    karusselltitel: 'Zentrum der Heiligungsbewegung',
    verzeichnispfad: 'Zentrum der Heiligungsbewegung',
    beitragtitel: 'Zentrum der Heiligungsbewegung',
    bild: 'maennedorf-zentrum-der-heiligungsbewegung/bild1.jpg',
    ort: 'Männedorf (ZH)',
    autor: 'Gergely Csukás',
    jahr: '2016',
    markierungen: [[47.25591, 8.69311]],
    kanton: Kantone.Zürich,
  },
  'Stiftskirche St. Leodegar': {
    karusselltitel: 'Stiftskirche St. Leodegar',
    verzeichnispfad: 'Stiftskirche St. Leodegar',
    beitragtitel: 'Zwischen Marienwallfahrt und Kulturkampf',
    ort: 'Schönenwerd (SO)',
    bild: 'schoenenwerd-stiftskirche/bild1.jpg',
    autor: 'Adrian Suter',
    jahr: '2016',
    markierungen: [[47.37193, 8.00439]],
    kanton: Kantone.Solothurn,
  },
  'Restaurant Blinde Kuh': {
    karusselltitel: 'Restaurant Blinde Kuh',
    verzeichnispfad: 'Restaurant Blinde Kuh',
    beitragtitel: 'Blinde Kuh – mehr als ein Restaurant',
    ort: 'Zürich',
    bild: 'zuerich-blindekuh/bild1.jpg',
    autor: 'Christoph Sigrist',
    jahr: '2016',
    markierungen: [[47.35834, 8.55719]],
    kanton: Kantone.Zürich,
  },
  'Schwarze Madonna': {
    karusselltitel: 'Schwarze Madonna',
    verzeichnispfad: 'Schwarze Madonna',
    beitragtitel: 'Wenn die «heilige Kranke» zur schwarzen Madonna geht...',
    bild: 'einsiedeln-madonna/bild1.jpg',
    ort: 'Einsiedeln (SZ)',
    autor: 'Ulrike Münger',
    jahr: '2015',
    markierungen: [[47.1267, 8.7523]],
    kanton: Kantone.Schwyz,
  },
};
